### ISSUE TITLE
AWS S3 compatible?

### ISSUE THREAD

**Issue by TheFrodo** [Zibbp/ganymede#104]
Greetings together,

I wanted to check if you can store the VODs on AWS (s3 compatible). 
That would be nice, because then you don't affect the storage space of the server too much.

**Comment by Zibbp** [comment]
Hi,
Currently there is no S3 API compatible storage support. Maybe this can be added in the future.

For now, if you're not already, you can mount a network share or block storage to the `/vods` volume to alleviate storage concerns on your server.

**Comment by TheFrodo** [comment]
I have already done this with wasabi. Unfortunately it does not show me the video + images. The error "The media could not be loaded, either because the server or network is down, or because the format is not supported." appears.

**Comment by Zibbp** [comment]
How are you exposing Wasabi as a block storage device that the API and Nginx can read?

**Comment by TheFrodo** [comment]
I took Wasabi's instructions and mounted it in the Linux system so that the server sees it as a normal folder.

Is that wrong?

**Comment by Zibbp** [comment]
I haven't done this before but I used [s3fs-fuse](https://github.com/s3fs-fuse/s3fs-fuse) which is what I'm assuming you are using. I had to add `user_allow_other` in `/etc/fuse.conf` as well as adding `-o allow_other` to the s3fs mount command. Everything is working as expected, just a little slow. Now sure if that is s3fs or Backblaze.
![image](https://user-images.githubusercontent.com/21207065/216824649-4b01ed3a-b883-4298-ba82-2ec3dab1de05.png)

![image](https://user-images.githubusercontent.com/21207065/216824659-2593fbb9-8380-4c7d-9cf1-8e8e82004ab5.png)

**Comment by TheFrodo** [comment]
It looks like that's works. 
Thank you for your quick help <3

A quick question: Can i edit the texts on the home page?

**Comment by Zibbp** [comment]
The home page text is all hardcoded in the [frontend repository](https://github.com/Zibbp/ganymede-frontend) so you are not able to change it. You can for the frontend repo and make changes but you will need to keep it up to date.

**Comment by TheFrodo** [comment]
Is it planned that you can change this by default. Or will there be a tutorial on how exactly this works.

**Comment by Zibbp** [comment]
No plan and no tutorial. I don't offer any customization support for things like that. If you would like to change stuff you will need to learn React and fork the frontend.

**Comment by TheFrodo** [comment]
Thank you for the support.
Have a nice day

**Comment by feavle** [comment]
Apologies to reopen a closed issue but is anyone else experiencing I/O errors when using Backblaze S2? I have a 20GB or so VOD and every time it reaches 5GB the upload freezes and eventually errors out with "ERRNO 5: I/O error"

**Comment by Zibbp** [comment]
Taking a quick look at s3fs-fuse issues, I've come across this one regarding a similar error https://github.com/s3fs-fuse/s3fs-fuse/issues/1547. It appears that setting `-o nomixupload` or `-o max_dirty_data=102400` was the fix for creator of the issue. I would try each of those, manually copying a large file to the mounted folder.

If that still doesn't work I would open an issue in the s3fs-fuse repository.

**Comment by feavle** [comment]
Aha, ended up solving the issue.

It completely crossed my mind that the VPS that I have has a SSD storage and a mounted HDD storage. s3fuse ended up using the 14GB SSD so the cache was filling up with the massive VOD file causing I/O errors.

In s3fuse you are able to designate the s3fuse cache folder so I set the parameter to the attached hdd storage. I then had an issue with 'connection closed' upon the VOD being downloaded and the parameter `-o nocopyapi` solved it. Here is my completed and working command:

`sudo s3fs mybucket /mnt/path -o allow_other -o max_dirty_data=102400 -o nocopyapi -o use_cache=/data/tmp -o passwd_file=/etc/passwd-s3fs -o url=https://url.to.s3/`

Thanks so much for creating this amazing application 😄
