### ISSUE TITLE
A 'Game Filter' setting per channel.

### ISSUE THREAD

**Issue by HStep20** [Zibbp/ganymede#111]
First off, absolutely love the app. Ive tried other twitch archivers in the past, but this is just incredible compared to those. 

As for the feature, it would be great if we could filter which type of stream downloads from a user. I watch some users who do both games as well as 'Software and Game Development', however, I only want to watch their Game Dev streams. 

Some sort of per-channel filter that would let you decide which 'game'/category of a stream to download (or multiple) would be great for channels like that.

**Comment by Zibbp** [comment]
Hi,
So a feature to select which categories or "chapters" to archive when archiving a channel's videos? Below is an image of Chapters that Twitch provides. If I only wanted "World of Warcraft" videos, I could select that in Ganymede and it would archive only videos that have a World of Warcraft chapter?
![image](https://user-images.githubusercontent.com/21207065/218319522-6a0af496-2160-447e-b2fe-4520de2a642c.png)

Would this feature be only for archiving a channel's videos/vods using the watched channel feature or extend it into archiving live streams. Not sure how it would work with live streams as the streamer could change categories later in the stream.

I could also save the categories in a new database table presenting them in the frontend with the ability to skip to that section.

**Comment by HStep20** [comment]
I don't use twitch much, but most streamers I watch do one thing per stream. I had [PirateSoftware ](https://www.twitch.tv/piratesoftware/videos?filter=archives&sort=time) in mind with this ask, who mostly does one thing per stream. 

You can look at his video archive and see that each stream is tailored to one game, but for streams with multiple chapters, I do like the idea of archiving it if it has a chapter that matches that 'chosen game' for the channel. Due to the 'logistics' of reading the stream live, I think it could be fine as an option only for the Watched Channel feature.

**Comment by Zibbp** [comment]
This feature has been released in [v1.2.4](https://github.com/Zibbp/ganymede/releases/tag/v1.2.4). Let me know if you encounter any issues.
