### ISSUE TITLE
Occasionally, an error occurs in Chat Converter.

### ISSUE THREAD

**Issue by kkr881** [Zibbp/ganymede#118]
Hi! I'm using Ganymede well.
However, I am inquiring because there are some problems with the use.

![화면 캡처 2023-02-22 001824](https://user-images.githubusercontent.com/11221246/220385713-31b22a72-f380-4578-a749-efbd0ad0806c.png)
Occasionally, Chat Download is completed, but an error occurs.

![화면 캡처 2023-02-22 002110](https://user-images.githubusercontent.com/11221246/220386204-4099b257-243d-4cf8-a7bb-bffbd5b50b23.png)
There is a normally down Chat JSON file, but an error occurs when restarting the task.

It is difficult to provide additional information because the Chat Convert LOG file is not created.

Thanks!

**Comment by Zibbp** [comment]
Appears the chat convert step is having difficulties getting the channel/user via Twitch's API. What is the channel name of the archive?

**Comment by kkr881** [comment]
The channel is currently temporarily banned, is that the reason?

**Comment by Zibbp** [comment]
Yes that would be the reason. The convert task needs channel information retrieved via the API. I would copy the live chat json from the container and wait until the channel is unbanned. Then the convert task can be rerun.
