### ISSUE TITLE
Bulk add and edit watched channels

### ISSUE THREAD

**Issue by NothingTV** [Zibbp/ganymede#122]
Just encountered a bug which caused a error "400 bad request" while checking the stream status, I think because of the amount of streams? Is there a limit for that? I had around 130 watched channels (only live streams). Due to that, I removed all watched channels and tried to re-add them, that solved the error 400 issue, but now I have to manually add all the channels back to the watched channels.

So my idea would be to add a bulk add (only change would be to give the API an array of channels to add with the same settings) + maybe bulk change the choosen channels.

Would that be possible?

**Comment by Zibbp** [comment]
The Twitch API [endpoint](https://dev.twitch.tv/docs/api/reference/#get-streams) used to check if a channel is live has a max of 100 IDs. This is what is probably causing the 400 error. I never expected someone to hit this limit 🤣. Implementing multiple requests if there are >100 IDs to check shouldn't be too difficult. As for bulk adding watched channels I can look into that as well.

How well is Ganymede holding up with that many watched channels? More specifically the queue. There must be quite a few active live stream queue items at once.

**Comment by NothingTV** [comment]
Ohhh, well yeah that makes sense :D
it worked really great for few hours, but I encountered several failures during the chat import, maybe also because of that limit (saw another issue concerning this, looks like it needs the API to renter it but it couldn't reach it due to the limit?). Oh and my CPU kinda exploded, but that's okay :D

Just played around with it to build a big public archive, didn't thought of it to be the first to hit that limit. Oops.
I'd happy to provide more details if it runs properly again if you need some stats but now I'm exhausted, because I have to manually re-add all of them, because I thought I somehow fked up the config and removed everything :(

**Comment by Zibbp** [comment]
Which task specifically had errors? Anything in the task logs or API container logs? There shouldn't be limits in any of those tasks as it's processing a single channel.

**Comment by NothingTV** [comment]
It failed several times during the chat_render Task, I couldn't see any errors in the Interface and I don't have any logs anymore, sorry.

**Comment by Zibbp** [comment]
The >100 channel fix and adding multiple watched channels at once has been released in [v1.2.5](https://github.com/Zibbp/ganymede/releases/tag/v1.2.5). Make sure to pull the latest API and frontend containers. Let me know if this fixes your issue.

**Comment by NothingTV** [comment]
Great update! Just re-added all channels (155 atm) to watched channels. I keep you posted in 1-2 days, thank you for the fast fix! :)

**Comment by NothingTV** [comment]
So small update. Over night until now everything went perfectly, beside several errors at the task **vod_download_thumbnail**.

**Comment by Zibbp** [comment]
Does it error as soon at that task is started or 20 minutes after as there is a task to re-run that `vod_download_thumbnail` 20 minutes after a live stream is started. Any logs in the API container? May need to enable `debug` in `config.json`.

**Comment by NothingTV** [comment]
Once directly after the **channel is live** notification and the latest 5 min after the VOD got marked as finished, I could find this in the API logs at the same time:
`{"level":"error","time":"2023-02-27T22:05:13+01:00","message":"no stream found"}`

debug is not enabled tho, hard to change anything now where the container run smoothly. But as far as I could see, it tried to grab the thumbnail, after the stream was already offline.

**Comment by Zibbp** [comment]
If you're not already I recommend to archive videos/vods for channels rather than live streams. It is more stable. I know that is not always possible as some channels do not have vods enabled or use dual audio tracks, etc.

**Comment by NothingTV** [comment]
Well the channels without active vods are the interesting ones, in Germany nearly every big channel has disabled vods because of the laws (DMCA etc) that's why I want to archive live streams.
Sad that everything works perfectly besides of the chat render (or convert).

**Comment by Zibbp** [comment]
Got it, there are a lot of German users of Ganymede and know I know why. Regarding the failures, post any logs (debug logs) here or create a new issue and I can help out. It would also help if you could upload problematic chat files.

**Comment by NothingTV** [comment]
Germany is a bit .. weird about all this.

Just enabled debug, there are many failures atm so I think I can submit few tomorrow. Thank you already in advance! :)

**Comment by NothingTV** [comment]
Okay, so here is a log of a failed **chat_render** task:
```
ganymede-api  | {"level":"error","error":"signal: segmentation fault (core dumped)","time":"2023-03-02T20:28:44+01:00","message":"error running TwitchDownloaderCLI for vod chat render"}
ganymede-api  | {"level":"error","error":"exit status 1","time":"2023-03-02T20:28:44+01:00","message":"error checking chat render logfile for no messages"}
ganymede-api  | {"level":"error","error":"exit status 1","time":"2023-03-02T20:28:44+01:00","message":"error rendering chat"}
```

but that looks like it does not help lol

**Comment by Zibbp** [comment]
Is there a log file for that chat render task? Click the console icon on the queue page. Could you upload one of the failing chat files by chance? You will need to exec into the container and navigate to `/tmp`.

>  I guess it would be great to have a limit of active queue items
There is, configurable in `config.json`. Live streams do not respect this number though as it needs to be recorded in real time and can't wait for the previous stream to finish.

**Comment by NothingTV** [comment]
There is a log file, but only with the usual progress logs, no errors. If that would help, I could give you access to the system tho. Sadly it's not stable enough yet, the tmp drive (2TB SSD storage) is completely full because it's not able to archive the VODs quicky enough because of the failures (I try to restart them after they failed)

**Comment by Zibbp** [comment]
> 252 queue items 

All live stream queue items? Damn! That could be the case that it can't handle it. Can you provide the name or two of streamers that have failed or continually fail on the chat render step? I want to see if I can reproduce it.

**Comment by NothingTV** [comment]
Sure, the streams of the streamer "dhalucard" often fails during the **chat_render** and **chat_convert** task.

Would it be possible to limit the active queue items? The CPU is really strong, but I guess no CPU could handle that much converts.

**Comment by Zibbp** [comment]
There already is a queue limit, but not for live streams. I can maybe look into limiting the number of chat renders active at once. But I don't know when I'll get around to that, busy with some other stuff right now.

In the mean time you can cut down on the number of what channels to see if that helps, or disable chat rendering and rely on the new chat player that doesn't use the video (you can still render the chats manually later on).

**Comment by NothingTV** [comment]
Yeah I mean the chat_render process, looks like this is the one that causes that high resource usage.

Alright, I give it a try thanks! :)

**Comment by NothingTV** [comment]
Besides of the TwitchDownloader issues, this works perfectly fine. I don't even need the the chat to be rendern, the .json is everything I need for my custom front-end.
The load is constantly below my expectations, thus I close this issue, since everything is solved. Thank you!
