### ISSUE TITLE
frontend and api manifest unavailable

### ISSUE THREAD

**Issue by yoharnu** [Zibbp/ganymede#126]
When running "docker-compose up", I get the following error for both ganymede-frontend and ganymede:
`Error response from daemon: Head "https://ghcr.io/v2/zibbp/ganymede/manifests/latest": received unexpected HTTP status: 503 Service Unavailable`

I am unable to pull those images.

**Comment by yoharnu** [comment]
After trying a few more times, it eventually worked.

**Comment by Zibbp** [comment]
Looks like Github Packages had an outage this morning https://www.githubstatus.com/incidents/bypf7bqdh4g0
