### ISSUE TITLE
Retention settings

### ISSUE THREAD

**Issue by yoharnu** [Zibbp/ganymede#127]
It would be great to be able to set a limit on how long videos are stored (e.g. 7 days) or maybe a limit to how much data (GB) is stored

**Comment by yoharnu** [comment]
Closing this in favor of a discussion

**Comment by CappiSteijns** [comment]
> It would be great to be able to set a limit on how long videos are stored (e.g. 7 days) or maybe a limit to how much data (GB) is stored

Dulicate of #115
