### ISSUE TITLE
An 'in progress' bar of videos on the landing page

### ISSUE THREAD

**Issue by HStep20** [Zibbp/ganymede#135]
Right now, opening Ganymede shows a big pane that takes up a lot of space without really contributing much and a row of 'recently archived' videos. While the big panel is a separate issue in how the UX could be improved, Id love to see a second row of videos above the 'recently archived' row of 'currently watching' streams. 

Since streams are so long, I rarely have the time to watch the whole thing in one go. Ill watch bits and pieces of it throughout a day or week, when I have the time. Sometimes its easy to find the stream I was in the middle of, but for people who have way more channels and streams archived, it may get annoying to find what they were watching before. 

Having a simple 'Currently Watching' line of videos on the homepage would remedy that issue, and make it easier for users to jump back in to what they were watching before. Ganymede already stores progress in videos, so I wouldn't think it'd be too difficult to add a new row based on videos that are 'in progress'

**Comment by Zibbp** [comment]
That's a great idea, I'll add it to the to-do list.

**Comment by Zibbp** [comment]
[v1.2.6](https://github.com/Zibbp/ganymede/releases/tag/v1.2.6) has been released which includes this feature.
