### ISSUE TITLE
Installationhelp ReverseProxy not working

### ISSUE THREAD

**Issue by TheFrodo** [Zibbp/ganymede#138]
Englisch is under this message.

Grüßt euch,

ich hab n kleines problem. Ich bekomme das reverse proxy nicht zum laufen. Ich habe soweit alles konfiguriert, und auch die SSL Zertifikate sind hinterlegt und aktiviert.
Nur wenn ich dann meine Seite aufrufe erhalte ich den Fehler in der Console. 

Kann mir da jemand helfen? ich bin komplett überfragt. :/ Ich geb auch gerne den Zugriff auf den Server weiter. 

=== ENG ===

Greetings,

I have a small problem. I can not get the reverse proxy to work. I have configured everything so far, and also the SSL certificates are deposited and activated.
Only when I then call my page I get the error in the console. 

Can someone help me? I am completely stumped. :/ I also like to give access to the server. 

![2023-03-09 11_38_17-Ganymede](https://user-images.githubusercontent.com/28831127/223999800-9720d683-27c5-4a81-9f99-8dff61f7ca84.png)

**Comment by Zibbp** [comment]
Can you post a redacted version of the docker-compose file without any secrets?

**Comment by TheFrodo** [comment]
Sure
https://pastebin.com/JHurv5v6

**Comment by TheFrodo** [comment]
I have tried also with the nignx proxy manager. 
Even though I have a little idea about it, I just can't get it to work. :/

**Comment by Zibbp** [comment]
Everything *looks* OK. Are there any errors in the API container logs? If you visit https://api.vodarchiv.net do you see the text "Ganymede API"? Can you try using a different browser that may not have cached this?

You will also need to add the `COOKIE_DOMAIN` env var as stated on the [reverse proxy page](https://github.com/Zibbp/ganymede/wiki/Reverse-Proxy).

**Comment by TheFrodo** [comment]
Have set the COOKIE_DOMAIN var.
when i go to the API page i get to the frontend.

This is too high for me, I think I'll just leave it :/ 
i just don't understand this. I think as a beginner I can not install this. I need a little more understanding for it

**Comment by Zibbp** [comment]
Sounds like you're not reverse proxying the services correctly if you receive the frontend when going to the API URL. I would do some research into reverse proxies and how to set them up.

**Comment by TheFrodo** [comment]
Greetings,

me again :D

One Little Problem do i have. See the attached screenshot.

everything works fine. But this is one error that i have

![2023-04-17 12_38_26-](https://user-images.githubusercontent.com/28831127/232461290-b47b3083-d0d1-4b1e-a02c-016c1aeff27d.png)
