### ISSUE TITLE
[Feature] Refresh channel avatar

### ISSUE THREAD

**Issue by soleny894** [Zibbp/ganymede#140]
Hi,

Can you add a way to refresh a channel avatar? I'm not sure if there's a current way to do it. 
Some streamers in my list changed their channel avatar but I can't update them from the interface. The only way seems to be manually by overriding the previous one.
Maybe a new button in "channels" can be added while editing a streamer to grab what's needed.

**Comment by Zibbp** [comment]
[v1.2.6](https://github.com/Zibbp/ganymede/releases/tag/v1.2.6) has been released which includes this feature. To update a channel's image, edit the channel in Admin > Channels and click the button.
![image](https://user-images.githubusercontent.com/21207065/224569347-a9222af6-f200-4799-bb53-4d2084a79ae9.png)
