### ISSUE TITLE
Commercial break even tho there is a auth-token

### ISSUE THREAD

**Issue by NothingTV** [Zibbp/ganymede#143]
I've subscribed to Twitch Turbo and added the correct Auth-Token in the interface, I don't get any errors with it but still there are VODs with commercial breaks. Is there anything I miss? Do I have to add another argument (--twitch-api-header=Authorization=OAuth abcdefghijklmnopqrstuvwxyz0123)? I thought it's enough to add the Key.

**Comment by Zibbp** [comment]
That is the correct way, adding that to Streamlink args. Can you check if the token you are using is still valid by following [Streamlinks docs](https://streamlink.github.io/cli/plugins/twitch.html#twitch) for fetching the token.

**Comment by NothingTV** [comment]
The token is still valid but I haven't added any new args.

**Comment by Zibbp** [comment]
Can you copy and paste all of your Streamlink args being sure to redact your token.

**Comment by NothingTV** [comment]
Right now I only have these default args: `--force-progress,--force,--twitch-low-latency,--twitch-disable-hosting`

Sorry, do I have to add the --twitch-api-header too? I'm confused because the Twitch Token is set in the Input "Twitch Token" already.

**Comment by Zibbp** [comment]
Yes, the api header argument need to be added as well. The "twitch token" field is for downloading sub-only VODs. The streamlink args are for live streams. Maybe I can combine these in the future to be less confusing. Here's an example of what your Streamlink args should look like.
```
--force-progress,--force,--twitch-low-latency,--twitch-disable-hosting,--twitch-api-header=Authorization=OAuth abcdefghijk12345
```

**Comment by NothingTV** [comment]
Yeah that's it, my bad, sorry, works with this arg.
