### ISSUE TITLE
Channel shows incorrect time in certain cases

### ISSUE THREAD

**Issue by kkr881** [Zibbp/ganymede#148]
There is a bug where if the live stream exceeds 24 hours, the exposure time on the channel is incorrect.
In the case of seconds-based playback time, it is stored normally,
but it seems that the time exposed to the channel is not normally exposed.
![화면 캡처 2023-03-18 181027](https://user-images.githubusercontent.com/11221246/226096487-701ea64a-c8fd-4d33-9ffe-89c5e07afd9d.png)
![화면 캡처 2023-03-18 180057](https://user-images.githubusercontent.com/11221246/226096519-2a383952-b73a-4a24-b447-a3188a53b7ad.png)

**Comment by Zibbp** [comment]
Hi,
This is fixed in https://github.com/Zibbp/ganymede-frontend/commit/ef1863b91bfcd591140d5e98f1452ea63b9c0c23. I'll close this issue when a release is published.
![image](https://user-images.githubusercontent.com/21207065/226181299-80a7511f-444e-4359-b3c1-705f44b118ba.png)

**Comment by Zibbp** [comment]
Released in [v1.2.7](https://github.com/Zibbp/ganymede/releases/tag/v1.2.7)
