### ISSUE TITLE
chat_move fails with rclone

### ISSUE THREAD

**Issue by NothingTV** [Zibbp/ganymede#150]
My setup uses a rclone mount to store the VODs, because the mount isn't the fasted (even with a HDD cache), the move task often fails. After a simple retry it works. Is there a way to "optimize" the move task or some kind of post_move_task, so once everything is done, you could start a upload script.

logs for the failed move:
`ganymede-api  | {"level":"error","error":"writing to output file failed: write /vods/channel/folder/vod_id-video.mp4: bad file descriptor","time":"2023-03-20T21:40:10+01:00","message":"error moving video"}`

**Comment by Zibbp** [comment]
The move task uses Golang's `io.copy` which is the recommended way to copy files. This is an Rclone issue. Have you looked into the error to see if there are any options you can enable that will help mitigate this? The first link when searching the error provided adding this config to your mount `--vfs-cache-mode writes`. Unsure what it does but I would so some research on the error.

**Comment by NothingTV** [comment]
You're right, I'm sorry. Works perfectly with the `vfs-cache-mode` arg. Thank you! :)
