### ISSUE TITLE
Start record of livestream.

### ISSUE THREAD

**Issue by Smallinger** [Zibbp/ganymede#156]
Hey is it possible to get a feature that you can start a record for a livestream like the archive function with video ID but for Livestreams ?
so that i don't need set it up in Watched Channels ?
for like streamers who i don't need all livestream recorded and can manuel start the recorder.

**Comment by Zibbp** [comment]
I can look into adding this functionality.

**Comment by Zibbp** [comment]
This has been added in [v1.2.8](https://github.com/Zibbp/ganymede/releases/tag/v1.2.8). Let me know if there are any issues.
