### ISSUE TITLE
Add date to recorded streams

### ISSUE THREAD

**Issue by c-hri-s** [Zibbp/ganymede#157]
Would it be possible to add the time a stream was recorded after the date?

If a streamer streams more than once on a given day it would be helpful to know when the stream started:

![image](https://user-images.githubusercontent.com/13216128/229242710-74492ddb-298d-4d8a-9aec-2fb69c0cbcc6.png)

**Comment by Zibbp** [comment]
Hovering over the date displays a tooltip with the time. Are you wanting the actual time behind the date like so? 
![image](https://user-images.githubusercontent.com/21207065/229243291-12fa196c-9d3f-4175-81ab-8c8e8fd6ff3a.png)

**Comment by c-hri-s** [comment]
Ah, didn't know about the tooltip.
But yes - I was suggesting something like in your screenshot so you could easily see what time the streamrecord started

**Comment by Zibbp** [comment]
I think that's too noisy to have on by default, but I can add an option on the profile page to enable that.

**Comment by c-hri-s** [comment]
Sounds good to me, thanks

**Comment by Zibbp** [comment]
Most things have tooltips that will display more information such as the title if it's longer than two lines.

**Comment by Zibbp** [comment]
This has been added in [v1.2.8](https://github.com/Zibbp/ganymede/releases/tag/v1.2.8). Let me know if there are any issues.

**Comment by c-hri-s** [comment]
Looks great, thanks!
