### ISSUE TITLE
Little error i think?

### ISSUE THREAD

**Issue by TheFrodo** [Zibbp/ganymede#171]
Greetings,

me again :D

One Little Problem do i have with reverse proxy. 
See the attached screenshot.

everything works fine. But this is one error that i have
![2023-04-17 12_38_26-](https://user-images.githubusercontent.com/28831127/232461525-7c11d7fe-9179-49f7-910a-489c6401eac7.png)

**Comment by Zibbp** [comment]
Looks like the frontend variable for `API_URL` is incorrect. Ensure it's set to `https://api.vodarchiv.net`

**Comment by TheFrodo** [comment]
that was it :D 

Now i have this

![qLwVZZpTa8](https://user-images.githubusercontent.com/28831127/233796732-4a4f3dcb-2a19-4a35-91bc-6dca05264729.png)

**Comment by Zibbp** [comment]
Is the API environment variable `FRONTEND_HOST` set to `https://vodarchiv.net`? Ensure that it is.
If you could post a censored version of your docker-compose file omitting sensitive information that would help.

**Comment by TheFrodo** [comment]
That was the problem I had only vodarchiv.net in there and not https://vodarchiv.net

I thank you anyway for helping. Now everything works
