### ISSUE TITLE
Add vod to queue?

### ISSUE THREAD

**Issue by HaagridTV** [Zibbp/ganymede#179]
Hi, is there a way (besides editing the db) to add a vod to the queue so you can re-download say corrupt chat or thumbnails?

I've imported a few vods from a different setup, having to add thumbnails and chat.
Sometimes the chat doesn't work. However those vods are so old that it doesn't really matter, twitch has removed them.

But the thumbnails. I got a few that doesn't have them.

I did run ffmpeg on all vods to take a screenshot and output in the folder with the correct filename.

Filename is the same as the db. But still doesn't show anything.

Looking at the info.json it just says 
`"thumbnail_url": "yes",`

Instead of
`"thumbnail_url":"https://static-cdn.jtvnw.net/cf_vods/uuid...ext_id..and.so.on..//thumb/thumb0-%{width}x%{height}.jpg"`

Even tho the db has the correct filepath for the thumbnail seems like it all falls apart if the info.json isn't set correctly?

So my question is do I have to insert the data in the info.json?

**Comment by Zibbp** [comment]
Hi,
The `info.json` is not used at all by Ganymede. It's saved for archival information for users. If you edit the VOD in Admin > Settings, is the "Web Thumbnail Path" set to the correct location? The frontend *only* uses the "web thumbnail" and not the "thumbnail" as the images are a smaller resolution and load faster. It may also be Nginx and/or your browser caching the non existent image.

There is not a way to add a VOD to the queue (if manually imported) other than to do it in the database. If the VOD is still available on Twitch you can just redownload it, but if it's not, then all the tasks would fail trying to fetch data that Twitch removed.

**Comment by HaagridTV** [comment]
Hi,

From the previous setup I had an info file with all the data I would need to import them to Ganymede.
So I wrote a script to gather all that data and import it to the database aswell as create folders, move files and rename accordingly.

After closer inspection I forgot to add the `ext_id` before the -thumbnail.jpg in the string.
My mistake.

And yea if twitch has removed the vod there is nothing to be done about it, I'll just add it manually in the DB if the need arises.

Thanks.
