### ISSUE TITLE
Add ability to delete VOD from channels page

### ISSUE THREAD

**Issue by c-hri-s** [Zibbp/ganymede#184]
It would be useful if you could choose to delete vods from the channel page using the 'three dot'' dropdown:

![image](https://user-images.githubusercontent.com/13216128/234545412-95342422-f9cf-4839-8292-fee8476a699b.png)

**Comment by Zibbp** [comment]
Good idea, while I'm at this I should also implement a delete files function. The current delete method in Ganymede does not remove any files, adding an option to include removing files has been requested a lot.

**Comment by c-hri-s** [comment]
I was going to ask if it could also delete files too - that would be amazing, thanks!

**Comment by Zibbp** [comment]
Released in [v1.2.12](https://github.com/Zibbp/ganymede/releases/tag/v1.2.12).

**Comment by c-hri-s** [comment]
Works great, thanks!
