### ISSUE TITLE
Question: Live Watched Channels

### ISSUE THREAD

**Issue by FirestrikeX** [Zibbp/ganymede#190]
By default live streams are checked every 5 minutes ([https://github.com/Zibbp/ganymede/wiki/Live-Stream-Archiving](https://github.com/Zibbp/ganymede/wiki/Live-Stream-Archiving)). Once a livestream is detected, lets say 3 minutes since the streams start, are the first 3 minutes of the streams fragments added to the start of the stream so that once the stream is finished, it is indistinguishable from the resulting VOD?

**Comment by Zibbp** [comment]
No, the archive starts at the time the queue job gets created. This can be reduced by setting the check interval to be lower.

**Comment by FirestrikeX** [comment]
> No, the archive starts at the time the queue job gets created. This can be reduced by setting the check interval to be lower. Or by just archiving the vod instead of a livestream (although that's not always possible).

Ah, thought so! Just wanted to check! Thanks for the quick reply!
