### ISSUE TITLE
Error when reading from stream

### ISSUE THREAD

**Issue by CappiSteijns** [Zibbp/ganymede#191]
Hi,

Currently I am in the progress of capturing a 24/7 live stream on [Twitch](https://www.twitch.tv/altijd_live). 

It happened a few times I deleted a ~40 GB file because there was an error during the `"video download"`. And when pressing `"restart"` it would fail and delete the file. 

Luckily the last time I got an error on `"video download"` it started a new capture, but it happened ~2 days later :P 

Was wondering if there could be something like a better error handling? 
And when I restart a `"video download"` it won't delete the old one in the` /temp` folder so I could manually add the few hours that were saved.

<details>
<summary>Logs on `"video download"</summary>
<br>
[download] Written 36.74 GiB to …-0242ac190005-video.mp4 (13h48m55s @ 0 bytes/s)
[download] Written 36.74 GiB to …-0242ac190005-video.mp4 (13h48m55s @ 0 bytes/s)
[download] Written 36.74 GiB to …-0242ac190005-video.mp4 (13h48m56s @ 0 bytes/s)
[download] Written 36.74 GiB to …-0242ac190005-video.mp4 (13h48m56s @ 0 bytes/s)
[download] Written 36.74 GiB to …-0242ac190005-video.mp4 (13h48m56s @ 0 bytes/s)[stream.hls][warning] Failed to reload playlist: Unable to open URL: https://video-weaver.ams02.hls.ttvnw.net/v1/playlist/CsoE4Vb9iiHlhc9lHsek-FKEfZxTDkvxDc7MieV3FooBl_11dJu3Sn-IWUuHS9bllwLvSORrEC2OjeA-Zz81JISrOzQ3a81YVJpyb6PUUpQKDIBeZ3raOtN_5_riCJtaZc3lKu4KtvWRjUdOQT_T8CWxNb8jDaUvbk1_6yhHwaiY_L-0QQdLgfftxsbLFMcfwdoe8VvJyRgoxTZpvydygXWiphKE_yaP2WXq1wCm7cdsyUxg56mY3T7KxW2qLXxQcaZRrefOk0B9eLindESSJXlNMgHV4Rs0D-7hgVQFtfTSW8k9dl3ZQvBedOcjXJgFC7EqDaLwg0rmdincsCnYSgeV9LLra5uDI66hnUjls0fkoRz8tjbea8ETHGlSywBWPDmOfZr_sQpoAlw6Nwkppy7TehJt2PKqf4aX4pkRiMMMm1E4nTPc0mHY-VYYEPaSVnevAKeELlybJHrWlbxTiJhxQYxV4-dP28RiyxrmwvllGag5f8UGqo5V6jSZUezBof2SP2eS608EuOHnkBMCIFfy7lrFDhhrcZrdbaMbaouj_7FYU0efNnDWZ4MLjFgcZtFawfyb9fuuakUk2tjMJigXRYKjuLdYSpljzfM6wXzSLSRRpa9Hw16MlF7yU0JAni4kFW3ezotsjwG9u4EOUtcichSqkQLUrN2s8bV0WDPnidzIE9F0JJw5xBnLEO_roCdMLaTsNTAtZGi8nNXVszqat9VykBQr42Tm4I_MUkvVkQY5W9Mclg4IMTVJsVwkpaCYnr0SLnO_JIOgvxoM2sya6eQ_9qUKdM8yIAEqCWV1LXdlc3QtMTCyAg.m3u8 (404 Client Error: Not Found for url: https://video-weaver.ams02.hls.ttvnw.net/v1/playlist/CsoE4Vb9iiHlhc9lHsek-FKEfZxTDkvxDc7MieV3FooBl_11dJu3Sn-IWUuHS9bllwLvSORrEC2OjeA-Zz81JISrOzQ3a81YVJpyb6PUUpQKDIBeZ3raOtN_5_riCJtaZc3lKu4KtvWRjUdOQT_T8CWxNb8jDaUvbk1_6yhHwaiY_L-0QQdLgfftxsbLFMcfwdoe8VvJyRgoxTZpvydygXWiphKE_yaP2WXq1wCm7cdsyUxg56mY3T7KxW2qLXxQcaZRrefOk0B9eLindESSJXlNMgHV4Rs0D-7hgVQFtfTSW8k9dl3ZQvBedOcjXJgFC7EqDaLwg0rmdincsCnYSgeV9LLra5uDI66hnUjls0fkoRz8tjbea8ETHGlSywBWPDmOfZr_sQpoAlw6Nwkppy7TehJt2PKqf4aX4pkRiMMMm1E4nTPc0mHY-VYYEPaSVnevAKeELlybJHrWlbxTiJhxQYxV4-dP28RiyxrmwvllGag5f8UGqo5V6jSZUezBof2SP2eS608EuOHnkBMCIFfy7lrFDhhrcZrdbaMbaouj_7FYU0efNnDWZ4MLjFgcZtFawfyb9fuuakUk2tjMJigXRYKjuLdYSpljzfM6wXzSLSRRpa9Hw16MlF7yU0JAni4kFW3ezotsjwG9u4EOUtcichSqkQLUrN2s8bV0WDPnidzIE9F0JJw5xBnLEO_roCdMLaTsNTAtZGi8nNXVszqat9VykBQr42Tm4I_MUkvVkQY5W9Mclg4IMTVJsVwkpaCYnr0SLnO_JIOgvxoM2sya6eQ_9qUKdM8yIAEqCWV1LXdlc3QtMTCyAg.m3u8)

[download] Written 36.74 GiB to …-0242ac190005-video.mp4 (13h48m56s @ 0 bytes/s)
[download] Written 36.74 GiB to …-0242ac190005-video.mp4 (13h48m57s @ 0 bytes/s)
[download] Written 36.74 GiB to …-0242ac190005-video.mp4 (13h48m57s @ 0 bytes/s)
[download] Written 36.74 GiB to …-0242ac190005-video.mp4 (13h48m57s @ 0 bytes/s)
[download] Written 36.74 GiB to …-0242ac190005-video.mp4 (13h48m57s @ 0 bytes/s)
[download] Written 36.74 GiB to …-0242ac190005-video.mp4 (13h48m58s @ 0 bytes/s)
[download] Written 36.74 GiB to …-0242ac190005-video.mp4 (13h48m58s @ 0 bytes/s)
[download] Written 36.74 GiB to …-0242ac190005-video.mp4 (13h48m58s @ 0 bytes/s)
[download] Written 36.74 GiB to …-0242ac190005-video.mp4 (13h48m58s @ 0 bytes/s)
[download] Written 36.74 GiB to …-0242ac190005-video.mp4 (13h48m59s @ 0 bytes/s)
[stream.hls][warning] Failed to reload playlist: Unable to open URL: https://video-weaver.ams02.hls.ttvnw.net/v1/playlist/CsoE4Vb9iiHlhc9lHsek-FKEfZxTDkvxDc7MieV3FooBl_11dJu3Sn-IWUuHS9bllwLvSORrEC2OjeA-Zz81JISrOzQ3a81YVJpyb6PUUpQKDIBeZ3raOtN_5_riCJtaZc3lKu4KtvWRjUdOQT_T8CWxNb8jDaUvbk1_6yhHwaiY_L-0QQdLgfftxsbLFMcfwdoe8VvJyRgoxTZpvydygXWiphKE_yaP2WXq1wCm7cdsyUxg56mY3T7KxW2qLXxQcaZRrefOk0B9eLindESSJXlNMgHV4Rs0D-7hgVQFtfTSW8k9dl3ZQvBedOcjXJgFC7EqDaLwg0rmdincsCnYSgeV9LLra5uDI66hnUjls0fkoRz8tjbea8ETHGlSywBWPDmOfZr_sQpoAlw6Nwkppy7TehJt2PKqf4aX4pkRiMMMm1E4nTPc0mHY-VYYEPaSVnevAKeELlybJHrWlbxTiJhxQYxV4-dP28RiyxrmwvllGag5f8UGqo5V6jSZUezBof2SP2eS608EuOHnkBMCIFfy7lrFDhhrcZrdbaMbaouj_7FYU0efNnDWZ4MLjFgcZtFawfyb9fuuakUk2tjMJigXRYKjuLdYSpljzfM6wXzSLSRRpa9Hw16MlF7yU0JAni4kFW3ezotsjwG9u4EOUtcichSqkQLUrN2s8bV0WDPnidzIE9F0JJw5xBnLEO_roCdMLaTsNTAtZGi8nNXVszqat9VykBQr42Tm4I_MUkvVkQY5W9Mclg4IMTVJsVwkpaCYnr0SLnO_JIOgvxoM2sya6eQ_9qUKdM8yIAEqCWV1LXdlc3QtMTCyAg.m3u8 (404 Client Error: Not Found for url: https://video-weaver.ams02.hls.ttvnw.net/v1/playlist/CsoE4Vb9iiHlhc9lHsek-FKEfZxTDkvxDc7MieV3FooBl_11dJu3Sn-IWUuHS9bllwLvSORrEC2OjeA-Zz81JISrOzQ3a81YVJpyb6PUUpQKDIBeZ3raOtN_5_riCJtaZc3lKu4KtvWRjUdOQT_T8CWxNb8jDaUvbk1_6yhHwaiY_L-0QQdLgfftxsbLFMcfwdoe8VvJyRgoxTZpvydygXWiphKE_yaP2WXq1wCm7cdsyUxg56mY3T7KxW2qLXxQcaZRrefOk0B9eLindESSJXlNMgHV4Rs0D-7hgVQFtfTSW8k9dl3ZQvBedOcjXJgFC7EqDaLwg0rmdincsCnYSgeV9LLra5uDI66hnUjls0fkoRz8tjbea8ETHGlSywBWPDmOfZr_sQpoAlw6Nwkppy7TehJt2PKqf4aX4pkRiMMMm1E4nTPc0mHY-VYYEPaSVnevAKeELlybJHrWlbxTiJhxQYxV4-dP28RiyxrmwvllGag5f8UGqo5V6jSZUezBof2SP2eS608EuOHnkBMCIFfy7lrFDhhrcZrdbaMbaouj_7FYU0efNnDWZ4MLjFgcZtFawfyb9fuuakUk2tjMJigXRYKjuLdYSpljzfM6wXzSLSRRpa9Hw16MlF7yU0JAni4kFW3ezotsjwG9u4EOUtcichSqkQLUrN2s8bV0WDPnidzIE9F0JJw5xBnLEO_roCdMLaTsNTAtZGi8nNXVszqat9VykBQr42Tm4I_MUkvVkQY5W9Mclg4IMTVJsVwkpaCYnr0SLnO_JIOgvxoM2sya6eQ_9qUKdM8yIAEqCWV1LXdlc3QtMTCyAg.m3u8)
[cli][info] Stream ended
error: Error when reading from stream: Read timeout, exiting
[cli][info] Closing currently open stream...
</details>

Edit: this might also be relevant: #192

**Comment by Zibbp** [comment]
Streamlink doesn't support streams longer than 24 hours, see https://github.com/streamlink/streamlink/issues/1058

Restarting the "video download" of a livestream is never a good idea (maybe I should add some warnings). What *should* happen is at 24 hours, streamlink will end and the chat download *should* also stop. At that point the channel is marked as offline and if the channel is still live, the channel will be added back to the queue at the next `live_check_interval`. This results in losing some of the stream, but is more manageable as you don't have a forever? stream being archived.

Do you recall if the chat download succeeded after the 24hour video download failed?
