### ISSUE TITLE
permissions error

### ISSUE THREAD

**Issue by Snuupy** [Zibbp/ganymede#193]
I have a ganymede instance set up from months ago, but for some reason I'm running into permissions errors. I've tried restarting ganymede containers, restarting the computer, etc. but the permissions error remains for some reason.

I've entered into a command line into the container via `docker exec -it ganymede-api /bin/bash` and created a folder in the mounting point to verify that it is able to do so, so I don't understand why it's unable to create folders or edit files.

In the queue, items error out and I'm unable to create folders even. It was working several releases ago so I'm not sure what changed.

```
ganymede-api       | {"level":"error","error":"mkdir /vods/healthygamer_gg/2023-04-21-1799740103-archive-5164e0ed-ea45-11ed-b33e-0242ac120004: permission denied","time":"2023-05-04T07:02:44Z","message":"error creating vod folder"}
ganymede-api       | {"level":"error","error":"error creating file: open /vods/xxxxx/2023-04-21-1799740103-archive-5164e0ed-ea45-11ed-b33e-0242ac120004/1799740103-video.mp4: permission denied","time":"2023-05-04T07:46:44Z","message":"error moving video"}
```

What do I need to do to fix this?

**Comment by Zibbp** [comment]
The vods directory is probably not owned or accessibly by the user running the API container. You can check who owns it by running `ls -lah /path/to/vods`. The owner should be the user the container runs as. By default the container runs as `911:911`. This can be changed by setting some custom environment variables to the docker compose for the API.
```
environment:
  - PUID=1000
  - PGID=1000
 ```

**Comment by Snuupy** [comment]
Thank you! That fixed it. For anyone else running into this, `id` will show you your current user/group ID. :)
