### ISSUE TITLE
Failed Download Thumbnail Blocking Progress

### ISSUE THREAD

**Issue by yoshi43** [Zibbp/ganymede#196]
I am having an issue when the thumbnail fails to download on a live stream, the stream or chat never start to download. I saw this mentioned in #51 and resolved in release [v1.0.7](https://github.com/Zibbp/ganymede/releases/tag/v1.0.7), but I am currently having the issue.

Please let me know what I can provide to help troubleshoot this. Thank you!

**Comment by Zibbp** [comment]
Hi, can you enable debug logging in `/data/config.json` (will require container restart) and upload some logs when this happens again? There are a few functions that could fail and I would like to see which one it is.

**Comment by yoshi43** [comment]
Here is a copy of the log while it is happening. I tried to trim it down as much as I could while still hopefully leaving in all the important information.

[004b3544cfe1e31612fcbae80b9aae71a4d2f73f5cfaae8a5765a4f5b3fc1e98-json copy.log](https://github.com/Zibbp/ganymede/files/11410613/004b3544cfe1e31612fcbae80b9aae71a4d2f73f5cfaae8a5765a4f5b3fc1e98-json.copy.log)

**Comment by Zibbp** [comment]
Looks like the Twitch API updates in one spot, but not another. Pushed a possible fix, can you try swapping the docker image tag to `:main` and trying again? `ghcr.io/zibbp/ganymede:main`

**Comment by yoshi43** [comment]
The issue is still happening under the :main docker image tag.
[1e89f5d87b7cab971697d69d5fc1c7a8bbaee52f6b2610f048a98d0d5da7e5b5-json.log](https://github.com/Zibbp/ganymede/files/11410681/1e89f5d87b7cab971697d69d5fc1c7a8bbaee52f6b2610f048a98d0d5da7e5b5-json.log)

**Comment by Zibbp** [comment]
Can you pull the latest `:main` image and try again?

**Comment by yoshi43** [comment]
I tested the latest :main image twice.

The first time it worked without issue. It started downloading the stream and chat without the thumbnail.

The second time it got stuck on the Save Info, which might be a totally separate issue, but I have attached that log as well. 
[ad677c473b4a45e2238f002df9400e71478261305136d2506df81ea636f0ecc3-json.log](https://github.com/Zibbp/ganymede/files/11410780/ad677c473b4a45e2238f002df9400e71478261305136d2506df81ea636f0ecc3-json.log)

**Comment by Zibbp** [comment]
What is the `live_check_interval` set to, or how often are you checking for livestreams *after* you start your stream? Twitch doesn't update all their API endpoints quick enough some times which can cause some issues.

**Comment by yoshi43** [comment]
I have it set to 1 second, which is obviously very low. I have Ganymede running in conjunction with another program that is checking for streams every second.

If the live_check_interval is the root of the problem I will tinker with both program’s setting to get them to sync up while working reliably.

Thank you for all your help!

**Comment by Zibbp** [comment]
Ya 1 second is too low, Twitch doesn't update fast enough. I'd say 5+ is safe from what I've tested.
