### ISSUE TITLE
Error deleting channel: foreign key constraint

### ISSUE THREAD

**Issue by c-hri-s** [Zibbp/ganymede#203]
I noticed that a channel I was following had changed their name, so I thought I would delete and re-add it (although I'm not actually sure this was necessary).

When trying to delete the channel I got this error:

Request Failed
error deleting channel: ent: constraint failed: pq: update or delete on table "channels" violates foreign key constraint "lives_channels_live" on table "lives"

From the db logs:

2023-05-12 07:26:51.833 UTC [34] ERROR:  update or delete on table "channels" violates foreign key constraint "lives_channels_live" on table "lives"
2023-05-12 07:26:51.833 UTC [34] DETAIL:  Key (id)=(11e62975-d8b4-4fe9-8312-56ad810366ce) is still referenced from table "lives".
2023-05-12 07:26:51.833 UTC [34] STATEMENT:  DELETE FROM "channels" WHERE "channels"."id" = $1

**Comment by Zibbp** [comment]
Do you have a watched channel entry for this channel? That may need to be deleted first (though, it should handle it, I'll look into fixing it). Also, deleting a channel will remove all VODs related to that channel. Make sure to edit any to the new channel first.

**Comment by c-hri-s** [comment]
No, it's a channel that's never had any clips recorded (they never went live since I added it)

**Comment by c-hri-s** [comment]
Also when you try to delete a channel it says in the text it WON'T delete anything, so you may wish to change the text (or behaviour - not sure which is right/wrong)

**Comment by Zibbp** [comment]
The wording needs to be updated, I meant it as it won't delete any files.

So there is not a watched channel entry for the old channel name, and you still can't delete the channel?

**Comment by c-hri-s** [comment]
Correct, yes. There's never been any recordings for that channel, no VODs

**Comment by Zibbp** [comment]
Strange, the error does say that there's an entry in `lives` for the channel. Can you run the following command on the server running Ganymede, replace the items in `< >` with the values in your environment.

```
docker exec -it <ganymede-db-container-name> psql -h localhost -p 5432 -U <db user> -d <db name> -c "SELECT * FROM lives;"
```

**Comment by c-hri-s** [comment]
```
                  id                  | watch_live | watch_vod | download_archives | download_highlights | download_uploads | download_sub_only | is_live | archive_chat | resolution |           last_live           | render
_chat |          updated_at           |          created_at           |             channel_live             
--------------------------------------+------------+-----------+-------------------+---------------------+------------------+-------------------+---------+--------------+------------+-------------------------------+-------
------+-------------------------------+-------------------------------+--------------------------------------
 f6e4d6a2-5330-4410-886e-512826a61a77 | t          | f         | t                 | t                   | t                | f                 | f       | t            | best       | 2023-03-10 15:25:45.888005+00 | t     
      | 2023-03-10 15:25:45.888005+00 | 2023-03-10 15:25:45.888005+00 | 11e62975-d8b4-4fe9-8312-56ad810366ce
 44906bb3-8d98-4227-b4a2-eb048fa2170b | t          | f         | t                 | t                   | t                | f                 | f       | t            | best       | 2023-04-13 23:28:16.731561+00 | t     
      | 2023-05-12 00:05:26.830647+00 | 2023-03-10 15:23:54.44405+00  | f2fb823b-be59-4fe6-ac90-0cac776b9e0e
 367d3c02-0556-4e25-83f2-8193aa3afb02 | t          | f         | t                 | t                   | t                | f                 | f       | t            | best       | 2023-05-03 14:27:49.166349+00 | t     
      | 2023-05-12 14:04:55.834839+00 | 2023-03-10 15:24:12.279029+00 | 194fb4bd-0d7d-4560-b55b-00243bcb49d5
 751f80a7-7f24-4fb5-865f-1613aabbabd1 | t          | f         | t                 | t                   | t                | f                 | t       | t            | best       | 2023-04-07 23:32:16.736628+00 | t     
      | 2023-05-12 21:01:59.387835+00 | 2023-03-10 15:26:48.826005+00 | d42cdff2-12cd-456f-82e3-0325e91549a6
 14c2c029-e4ad-470d-ae20-9807a913d188 | t          | f         | t                 | t                   | t                | f                 | t       | t            | best       | 2023-05-06 02:03:29.856548+00 | t     
      | 2023-05-12 21:07:59.40163+00  | 2023-03-10 15:24:04.879157+00 | fca33af2-fdab-4cd0-8e46-81812d9d0fb0
 5dafb57d-605a-4783-8361-c0342b82833f | t          | f         | t                 | t                   | t                | f                 | f       | t            | best       | 2023-03-17 20:32:21.293055+00 | t     
      | 2023-03-28 20:01:28.391299+00 | 2023-03-10 15:26:57.566443+00 | d21ac68e-bd9d-4e81-8eb5-117847e9fe29
 13a974b1-f837-4198-be20-2b2de874894e | t          | f         | t                 | t                   | t                | f                 | f       | t            | best       | 2023-03-10 15:24:18.944738+00 | t     
      | 2023-05-07 20:47:00.842198+00 | 2023-03-10 15:24:18.944739+00 | 90b3f9f2-1aa6-4cb8-9a15-0068517a58cb
(7 rows)
```

**Comment by Zibbp** [comment]
The watched channel in Admin > Watched Channels doesn't show with the id of `f6e4d6a2-5330-4410-886e-512826a61a77`?

**Comment by c-hri-s** [comment]
Ignore me. I completely misunderstood what you were saying.
Yes - there's a watched channel entry - I thought you meant was there watched clips (as in vods saved).

**Comment by Zibbp** [comment]
Deleting that watched channel should allow you to delete the channel
