### ISSUE TITLE
every feresh -> new login

### ISSUE THREAD

**Issue by DJKenzoDE** [Zibbp/ganymede#204]
good day :D 

i have set the cookie domain but with every refresh of the page (Simple F5) than the page give me the 401 noit authorized and i have to login again.

**Comment by Zibbp** [comment]
If you have Ganymede running on a subdomain try setting `COOKIE_DOMAIN=ganymede.domain.net` or if it's already that, try `COOKIE_DOMAIN=domain.net`

**Comment by DJKenzoDE** [comment]
Yeah it's running on a subdomain, i test it later with the domain (domain.tls)

**Comment by DJKenzoDE** [comment]
the result of the origin domain is the same. page reload ends in new login

**Comment by DJKenzoDE** [comment]
i have found the solution:

the cookie domain doesnt have the scheme (https | http) and it must the subdomain (vod.domain.tld | frontend domain)
