### ISSUE TITLE
files/channels not available to see omage or videos

### ISSUE THREAD

**Issue by DJKenzoDE** [Zibbp/ganymede#208]
here is my problem:

i have archived a 30 sec stream to test it and it say itd downloaded it and all other things nad merged it but i cant see the images(profil picture) and the downloaded vod

screenshot from the error: https://share.djkenzo.de/lEho2/zUfAhUno45.png

**Comment by Zibbp** [comment]
If you can't see images or the video it's probably a Nginx related issue. Ensure the nginx container is running, has the correct config, and the correct URL is present in the frontend container environment variables that points to the nginx container.

**Comment by DJKenzoDE** [comment]
Yeah, it's all perfect I think?

Can I send the docker compose file and you say it's perfect or has errors?

**Comment by DJKenzoDE** [comment]
here is the error and i think i know the issue: https://share.djkenzo.de/lEho2/yeZOBAyE58.png
the file its createt but with the suffix "-convert" and i dont have edit templates or other things: https://share.djkenzo.de/lEho2/xoHaBaMi65.png

**Comment by DJKenzoDE** [comment]
i have been multiply steps forward and now i have the problem that the nginx say 403 forbidden and i didnt touch the nginx config
