### ISSUE TITLE
Hi from the author of Mantine DataTable!

### ISSUE THREAD

**Issue by icflorescu** [Zibbp/ganymede#225]
Hey @Zibbp,

This is @icflorescu, the author of [Mantine DataTable](https://icflorescu.github.io/mantine-datatable/) open-source component.

I recently discovered you are using Mantine DataTable in this repo.
Would you care to share a bit of feedback with me regarding your experience with it?
I'm trying to understand the users' stories and experience with my component in order to see how/if I could further improve the project.

Also, I'm planning to compile a list of startups / projects that are using Mantine DataTable and add it to the project's documentation website. Would you be ok with me adding a logo/link to [Zibbp/ganymede-frontend](https://github.com/Zibbp/ganymede-frontend)?

Thanks a lot for using [Mantine DataTable](https://icflorescu.github.io/mantine-datatable/) and apologies for approaching you like this!

Cheers,
Ionut

**Comment by Zibbp** [comment]
Hey
Thanks for stopping by! I'm not doing anything too advanced with Mantine DataTables but it's been working great for my needs and it was extremely simple to setup. Coming from VueJS it's nice to see a large number of open source UI frameworks and other developers making packages that complement it. I can't think of any improvements. 

Feel free to add Ganymede to that list. Thanks!

**Comment by icflorescu** [comment]
Thanks a lot!
