### ISSUE TITLE
Nginx permission issue(?)

### ISSUE THREAD

**Issue by disgjaiidk** [Zibbp/ganymede#226]
I'm running Ganymede on Unraid with docker compose, up until recently my config was working fine. But now the nginx container now doesn't seem to have permission to _something_ (I don't know alot about this).
I have tried changing a few folder ownerships to root etc. and even given the nginx config the PUID/PGID for root with no luck.
<sub> 
2023/06/10 19:22:44 [notice] 1#1: nginx/1.25.0
2023/06/10 19:22:44 [notice] 1#1: built by gcc 10.2.1 20210110 (Debian 10.2.1-6) 
2023/06/10 19:22:44 [notice] 1#1: OS: Linux 5.19.17-Unraid
2023/06/10 19:22:44 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 40960:40960
2023/06/10 19:22:44 [notice] 1#1: start worker processes
2023/06/10 19:22:44 [notice] 1#1: start worker process 22
2023/06/10 19:22:44 [alert] 22#22: setrlimit(RLIMIT_NOFILE, 65535) failed (1: Operation not permitted)
2023/06/10 19:22:44 [notice] 1#1: start worker process 23
2023/06/10 19:22:44 [alert] 23#23: setrlimit(RLIMIT_NOFILE, 65535) failed (1: Operation not permitted)
2023/06/10 19:22:44 [notice] 1#1: start worker process 24
2023/06/10 19:22:44 [alert] 24#24: setrlimit(RLIMIT_NOFILE, 65535) failed (1: Operation not permitted)
2023/06/10 19:22:44 [notice] 1#1: start worker process 25
2023/06/10 19:22:44 [alert] 25#25: setrlimit(RLIMIT_NOFILE, 65535) failed (1: Operation not permitted)
2023/06/10 19:22:44 [notice] 1#1: start worker process 26
2023/06/10 19:22:44 [alert] 26#26: setrlimit(RLIMIT_NOFILE, 65535) failed (1: Operation not permitted)
2023/06/10 19:22:44 [notice] 1#1: start worker process 27
2023/06/10 19:22:44 [alert] 27#27: setrlimit(RLIMIT_NOFILE, 65535) failed (1: Operation not permitted)
2023/06/10 19:22:44 [notice] 1#1: start worker process 28
2023/06/10 19:22:44 [alert] 28#28: setrlimit(RLIMIT_NOFILE, 65535) failed (1: Operation not permitted)
2023/06/10 19:22:44 [notice] 1#1: start worker process 29
2023/06/10 19:22:44 [alert] 29#29: setrlimit(RLIMIT_NOFILE, 65535) failed (1: Operation not permitted)
2023/06/10 19:22:44 [notice] 1#1: start worker process 30
2023/06/10 19:22:44 [alert] 30#30: setrlimit(RLIMIT_NOFILE, 65535) failed (1: Operation not permitted)
2023/06/10 19:22:44 [notice] 1#1: start worker process 31
2023/06/10 19:22:44 [notice] 1#1: start worker process 32
2023/06/10 19:22:44 [notice] 1#1: start worker process 33
2023/06/10 19:22:44 [alert] 31#31: setrlimit(RLIMIT_NOFILE, 65535) failed (1: Operation not permitted)
2023/06/10 19:22:44 [alert] 33#33: setrlimit(RLIMIT_NOFILE, 65535) failed (1: Operation not permitted)
2023/06/10 19:22:44 [alert] 32#32: setrlimit(RLIMIT_NOFILE, 65535) failed (1: Operation not permitted)
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: IPv6 listen already enabled
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
</sub>

**Comment by Zibbp** [comment]
Ganymede ships with the standard upstream Nginx image. I would search the web with the `setrlimit(RLIMIT_NOFILE, 65535) failed (1: Operation not permitted)` error and see what you find. I don't believe it's a Ganymede issue.
