### ISSUE TITLE
Delete files slider only works fro /admin/vods?

### ISSUE THREAD

**Issue by c-hri-s** [Zibbp/ganymede#237]
The 'delete files' slider doesn't seem to be working on the individual channel page, only from the vod list.
Is this by design? It didn't used to be this way.

If I visit /admin/vods then I can choose the trashcan and then have the option to select the delete files slider.

If I visit /channels/bknights89 (for example), then when I go to the 3 dots and select 'delete', I see the delete files slider, but you can't select it.

**Comment by Zibbp** [comment]
I never added support for deleting the channel and all videos when I implemented the "delete files" slider. I'll look into adding this.

**Comment by c-hri-s** [comment]
It used to work in previous versions, perhaps unintentionally.
Thanks for considering adding it

**Comment by Zibbp** [comment]
I misread what you originally meant. I fixed the "delete files" slider in the video menu in https://github.com/Zibbp/ganymede-frontend/pull/12 and hope to have it released sometime this weekend.

**Comment by c-hri-s** [comment]
That's great, thank you!

**Comment by Zibbp** [comment]
Fix released in https://github.com/Zibbp/ganymede/releases/tag/v1.3.2

**Comment by c-hri-s** [comment]
Confirmed fixed, thanks
