### ISSUE TITLE
File/folder paths break when # is in path

### ISSUE THREAD

**Issue by russelg** [Zibbp/ganymede#250]
My folder template is `{{date}} - {{title}} [{{id}}][{{type}}][{{uuid}}]` and my file template is `{{title}} [{{id}}]`.

This can (and does) break when a stream has a # in the title, e.g. `Midnight Snacks #955: 07.12.23 - presented by W.T. Snacks`.

This results in requests like so: `/vods/midnightsnacksfm/2023-07-12%20-%20Midnight_Snacks_#955__07.12.23_-_presented_by_W.T._Snacks%20[48844459693][live][6ce097e2-2068-11ee-9b03-0242ac120005]/Midnight_Snacks_#955__07.12.23_-_presented_by_W.T._Snacks%20[48844459693]-thumbnail.jpg`. 

The browser strips the # for the server request, and the end URL is `/vods/midnightsnacksfm/2023-07-12%20-%20Midnight_Snacks_`

I think it would be satisfactory to either escape the URL where it is used or add # to `utils.SanitizeFileName`.
\# is a valid filename character, so I would think making sure the URL is escaped correctly would be the correct solution here.

**Comment by Zibbp** [comment]
I merged https://github.com/Zibbp/ganymede-frontend/pull/13 and is available on the `:main` image tag for the frontend if you'd like to try it out.

**Comment by russelg** [comment]
Just tested it, works great. Thanks for fixing it so quickly!
