### ISSUE TITLE
It is not possible to activate retention

### ISSUE THREAD

**Issue by CrushTub3** [Zibbp/ganymede#251]
Hello,

I tried to activate retention, but it did not work.
I get the message: 

> Channel Updated
> Channel has been updated successfully

When the channel is edited again, the setting is not marked as active.
I have tested different browsers. The result is the same everywhere.
After that I have completely reinstalled Ganymede. Even after that it was not possible to activate the setting.

```
Frontend
Version:
d811af37881eeb0436f1f1eb99972cdd745366c6-2023-5-30
API
Version:
Build Date:
2023-04-06T00:26:32Z
Git Commit Hash:
44d63977359ced1869f2157ec33b2ea8597db2c9
Uptime:
16m38.679016907s
Package Versions
FFmpeg:

ffmpeg version 4.3.5-0+deb11u1 Copyright (c) 2000-2022 the FFmpeg developers
built with gcc 10 (Debian 10.2.1-6)
configuration: --prefix=/usr --extra-version=0+deb11u1 --toolchain=hardened --libdir=/usr/lib/aarch64-linux-gnu --incdir=/usr/include/aarch64-linux-gnu --arch=arm64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
libavutil      56. 51.100 / 56. 51.100
libavcodec     58. 91.100 / 58. 91.100
libavformat    58. 45.100 / 58. 45.100
libavdevice    58. 10.100 / 58. 10.100
libavfilter     7. 85.100 /  7. 85.100
libavresample   4.  0.  0 /  4.  0.  0
libswscale      5.  7.100 /  5.  7.100
libswresample   3.  7.100 /  3.  7.100
libpostproc    55.  7.100 / 55.  7.100

TwitchDownloader:
TwitchDownloaderCLI 1.52.3
Chat Downloader:
0.2.4
Streamlink:
streamlink 5.3.1 
```

**Comment by Zibbp** [comment]
> Build Date:
2023-04-06T00:26:32Z

It appears your build date is old. Are you running the `:latest` tags for both the API and frontend images?

**Comment by CrushTub3** [comment]
Both Container running with :latest tag.

![ganymede](https://github.com/Zibbp/ganymede/assets/17006503/05080686-aca0-486b-a582-fedea593196d)

I used the docker-compose.yml from the repo and modified it to my needs.

**Comment by Zibbp** [comment]
Is this running on x86 or ARM? Can you click into the "ganymede-api" container in Portainer and copy/paste the image including the hash? 
![image](https://github.com/Zibbp/ganymede/assets/21207065/11438bcd-2134-4806-abd3-21776c7a7b03)

**Comment by CrushTub3** [comment]
Running on arm64 (Raspberry Pi 4).
`Image 	ghcr.io/zibbp/ganymede:latest@sha256:1df3231ddfca7129e78a267aeee5ecac42c0f579f606e436e35316dc20ba9879`

**Comment by Zibbp** [comment]
I tested on an Oracle ARM instance and I'm running the latest version. Can you confirm that you're running the latest? `docker compose pull` says the images are the latest?
![image](https://github.com/Zibbp/ganymede/assets/21207065/e5e19c96-bc66-4168-9df9-b06c0e3902a1)

**Comment by CrushTub3** [comment]
OK, as I have now found out from the tips and questions, my Portainer installation seems to be bugged.

Even when I specify to repull the image, it is not repulled.
So after I just removed the stack and the images, I can activate retention.

Thanks for the support
