### ISSUE TITLE
[Ask] Record with stdout and ffmpeg stdin

### ISSUE THREAD

**Issue by lucas19961** [Zibbp/ganymede#267]
Hello there! Is it feasible to utilize the Streamlink stdout option for recording and then redirecting it to ffmpeg in order to obtain a smaller file size? This technique, which I currently use through a batch script, allows me to record 8-hour VODs with good quality while keeping the file size around 8-10 GB.

**Comment by Zibbp** [comment]
There's a post-video ffmpeg task that you can modify in Admin > Settings. This does not have any hardware acceleration. 
![image](https://github.com/Zibbp/ganymede/assets/21207065/344c37c4-88b4-4fd0-bcea-db10599f0171)

If you want more advanced options such as hardware acceleration, I use [Tdarr](https://home.tdarr.io/) which periodically scans the vods folder and re-encodes to AV1.

**Comment by lucas19961** [comment]
My idea was this `streamlink  "--twitch-disable-hosting https://www.twitch.tv/channel best  -O  | ffmpeg -i pipe:0 -c:v libx264 -crf 23 -maxrate 4M -bufsize 24M -preset veryfast -movflags faststart /home/VOD/channel/out-$date.mp4` this is not possible ? @Zibbp

**Comment by Zibbp** [comment]
There is no support for piping the Streamlink output to ffmpeg. You're recommended to place your streamlink args in the setting input for it `-c:v libx264 -crf 23 -maxrate 4M -bufsize 24M -preset veryfast -movflags faststart`.
