### ISSUE TITLE
Increasing the frequency of checking new videos to archive

### ISSUE THREAD

**Issue by ben-watt-es** [Zibbp/ganymede#282]
Is it possible to increase the frequency that ganymede checks for new vods to archive?

I'd like to archive the vods of a streamer that often deletes their streams a few hours after broadcast. Manually adding the vod id works but it often ends up last in the queue and the vod can be gone by the time that item is reached.

**Comment by Zibbp** [comment]
Currently there is no way to increase the frequency of that schedule. It is hard coded to run daily.

https://github.com/Zibbp/ganymede/blob/d575e1b908ac2af28c1353394c44151198633f8f/internal/scheduler/scheduler.go#L142

I can add a config entry, similar to the live stream check interval, that users can modify.

**Comment by Blaiz0** [comment]
While I in no way oppose to have a variable for this function, that could be nice. I think a better solution for the issue described, is to archive live streams instead of VODs. Have you looked at this option?

**Comment by ben-watt-es** [comment]
I do also archive live streams. There are tradeoffs. If I'm subscribed to a channel, then the ad-free live stream is usually the best option. However sometimes it gets divided up into multiple segments for some reason. 
If I'm not subscribed, then the live stream with ad breaks and pitch shifting to catch up is almost always worse than the vod. But sometimes copyrighted audio is present, in which case the vod is the worse option.
So I archive both and choose the one with the least amount of problems.

**Comment by Zibbp** [comment]
[v1.4.2](https://github.com/Zibbp/ganymede/releases/tag/v1.4.2) has been released which includes a config setting to configure when the video schedule runs, configurable in minutes.

> If I'm not subscribed, then the live stream with ad breaks and pitch shifting to catch up is almost always worse than the vod.

There's a "proxy" feature that proxies the live stream download through one of the public providers. Have you tried that? It's definitely not as good as straight from Twitch but the ad breaks and pitch issue is even worse.

**Comment by ben-watt-es** [comment]
I have been using this for past few days now, and it is working perfectly. Thanks again.
