### ISSUE TITLE
[Feature Request] Auto upload VOD to Youtube

### ISSUE THREAD

**Issue by Aerglonus** [Zibbp/ganymede#320]
After completing the video rendering process, would be nice to have the option to automatically upload the rendered video to YouTube as a backup option.

**Comment by Zibbp** [comment]
Hi,
Uploading to Youtube is out of scope for this project. I intended it to be local only. You can likely script something up that could automatically upload videos to Youtube using the [API](https://github.com/Zibbp/ganymede/tree/main/docs).
