### ISSUE TITLE
sharp is required to be installed in standalone mode | failed to write image

### ISSUE THREAD

**Issue by KyuubiDDragon** [Zibbp/ganymede#369]
Hello, if i try to login, the frontend send me the following error:

im using this docker compose: https://github.com/Zibbp/ganymede/blob/main/docker-compose.yml

⨯ Failed to write image to cache glb7upp0hmHcWnmyFAqzryPDm2TLshIlu-ssBHDOOfE= [Error: EACCES: permission denied, mkdir '/app/.next/cache/images'] {

⨯ Error: 'sharp' is required to be installed in standalone mode for the image optimization to function correctly. Read more at: https://nextjs.org/docs/messages/sharp-missing-in-production

**Comment by KyuubiDDragon** [comment]
Hello, after i  had an issue in my docker config. now the login works. But nice, that the other issue will be fixed soon

**Comment by KyuubiDDragon** [comment]
A short feedback:
With the api changes, theres the workflow tab that doesnt work.
All the other tabs works fine.

f8 error
`TypeError: w is undefined
    NextJS 69
[_app-460189a8d20acafc.js:9:2661](http://192.168.50.51:4801/_next/static/chunks/pages/_app-460189a8d20acafc.js)
TypeError: w is undefined
    NextJS 69
[_app-460189a8d20acafc.js:9:2661](http://192.168.50.51:4801/_next/static/chunks/pages/_app-460189a8d20acafc.js)
A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred [_app-460189a8d20acafc.js:9:2661](http://192.168.50.51:4801/_next/static/chunks/pages/_app-460189a8d20acafc.js)`

**Comment by Zibbp** [comment]
This has been fixed in the latest release [v2.1.0](https://github.com/Zibbp/ganymede/releases/tag/v2.1.0).
