### ISSUE TITLE
Can only sometimes log in.

### ISSUE THREAD

**Issue by nothing2obvi** [Zibbp/ganymede#388]
Hello, I was able to get ganymede working via Docker, and at first wasn't able to log in, but then after restarting the temporal container I was able to log in. I had to restart all the containers because I tried to fix something in the nginx.conf because the [profile pictures weren't showing](https://github.com/Zibbp/ganymede/issues/67), and couldn't log in. I tried reverting the changes to the nginx.conf and restarting all the containers, then I was able to log in, again, after restarting the temporal container. I had to completely quit Docker to restart my Mac, but I can't log back into ganymede. I tried completely removing the containers then starting them up again, and I still can't log in. Even restarting the temporal container won't help.

I'd appreciate any help on this. Thanks.

**Comment by Zibbp** [comment]
Are the API and Frontend container ENV vars configured to point to an internal/public IP/hostname? It cannot be `localhost`
```
       - FRONTEND_HOST=http://IP:PORT
...
      - API_URL=http://IP:PORT # Points to the API service
      - CDN_URL=http://IP:PORT # Points to the CDN service
```

**Comment by nothing2obvi** [comment]
Thanks for your quick response. Yes they are pointing at an internal IP. For now the login issues have stopped but I'll give it a few days to experiment with needing to log in again, and if it works just fine, I'll close the issue. I've found that restarting the temporal container helps.

**Comment by Zibbp** [comment]
Strange. The temporal container isn't used for authentication so something else is wrong somewhere.

**Comment by nothing2obvi** [comment]
Still happens. If I either restart the temporal container or sometimes the api container it will work.

**Comment by Zibbp** [comment]
Any logs in the API container? I noticed that the API service doesn't have a depends_on for a required dependency. Try adding the following to the API container service
```
    depends_on:
      - ganymede-temporal
```
