### ISSUE TITLE
Limit archive grab age

### ISSUE THREAD

**Issue by noraemsu** [Zibbp/ganymede#395]
Is there a way to limit the "Archive past channel videos." to the past 365 days for example?
I noticed it was creating folders and files for past broadcasts since 2017 and forward for a channel I added.

Or if it's not possible would this be a potential future feature?

Thanks!

**Comment by Zibbp** [comment]
A time frame constraint doesn't exist for this. I'll look into adding this feature.

**Comment by Zibbp** [comment]
I've added a "max video age" field when adding/editing a watched channel in [v2.2.0](https://github.com/Zibbp/ganymede/releases/tag/v2.2.0).
