### ISSUE TITLE
Invalid Date (Start and Close Time)

### ISSUE THREAD

**Issue by urbnywrt** [Zibbp/ganymede#412]
![image](https://github.com/Zibbp/ganymede/assets/14278436/65c28bd1-52a1-4657-8fee-391ff477d44c)
Start and Close Time is Invalid Date on workflows page
Timezone in both compose and timezonectl is set to Europe/Moscow
Same for all items in workflows page, in temporal ui time is correct

**Comment by Zibbp** [comment]
Fixed in https://github.com/Zibbp/ganymede-frontend/pull/29, thanks for the report.
