### ISSUE TITLE
Twitch name change

### ISSUE THREAD

**Issue by CappiSteijns** [Zibbp/ganymede#423]
Hi,

I'm encountering an issue where if a user changes their account name, Ganymede doesn't update this change. However, when I manually add a new channel (which isn't actually new), it says the account already exists, which I understand.

![image](https://github.com/Zibbp/ganymede/assets/84481241/d37d71a3-505e-4ef3-978f-af44afe07e95)

I can manually change the "name":
![image](https://github.com/Zibbp/ganymede/assets/84481241/2e600c59-fe17-4332-a9e3-5f3bbfdb7228)

But then it doesn't work when the account goes live.

What is the best practice when a user changes their account name?

**Comment by Zibbp** [comment]
Is the first screenshot the name channel name? It should just work if you update the `name` field when editing the channel. If you have debug logging enabled can you check what user is being queried when the live stream check runs?
```
{"level":"debug","time":"2024-05-10T18:20:18-05:00","message":"getting live streams using the following query param: ?user_login=foo"}
```

**Comment by CappiSteijns** [comment]
> Is the first screenshot the new channel name? It should just work if you update the `name` field when editing the channel. If you have debug logging enabled can you check what user is being queried when the live stream check runs?
> 
> ```
> {"level":"debug","time":"2024-05-10T18:20:18-05:00","message":"getting live streams using the following query param: ?user_login=foo"}
> ```

Ah yes, changing the name does indeed work. But for some reason something went wrong with 1 channel who has updated his name.  Altijd_live to RadioHDFM. It is not listed anymore in the api log.

```DBG getting live streams using the following query param: ?user_login=coffeestainstudiosdevs&user_login=lekkerspelen&user_login=EasyStacks&user_login=gamemeneer&user_login=bardo&user_login=egbertlive```

**Comment by Zibbp** [comment]
Can you delete and re-add the watched channel entry for that channel, and check if it's listed in the live stream check log?

**Comment by CappiSteijns** [comment]
ah now it does indeed show up in the api logs: ```message=getting live streams using the following query param: ?user_login=coffeestainstudiosdevs&user_login=lekkerspelen&user_login=EasyStacks&user_login=gamemeneer&user_login=bardo&user_login=RadioHDFM&user_login=egbertlivetime=2024-05-12T16:59:19+02:00```
