### ISSUE TITLE
Adaptive Streaming

### ISSUE THREAD

**Issue by MadMakz** [Zibbp/ganymede#43]
First of all awesome project! Thanks for this, the only thing i'm missing is adaptive streaming of the stored files.

**Comment by Zibbp** [comment]
Hi, I'm not sure what you mean by adaptive streaming. Can you provide some more information?

**Comment by Zibbp** [comment]
That is out of scope for this project as I believe it does not help the archival of VODs. This is something that can be implemented on your end by running ffmpeg on VOD completion webhooks.
