### ISSUE TITLE
Feature Request: Per Channel Settings

### ISSUE THREAD

**Issue by ccKep** [Zibbp/ganymede#430]
This is a feature Request: It would be great if we could enable per-channel settings to override the default settings regarding ffmpeg / twitch-downloader or the storage template.

I have some channels where I only want to store audio for example, so it would be great if I could provide the necessary settings (ffmpeg arguments and perhaps storage template / file extensions, maybe even twitch-downloader args to only record audio at all) so that I can set these channels to record to mp3 only.

The player can play these back just fine, at the moment I manually convert them and change the video-filename in the VODs to the mp3.

**Comment by Zibbp** [comment]
I want to keep the storage template has a global setting. I also don't want users to modify the file extensions as 1) browsers are very picky about video containers and codecs (e.g. Firefox and MKV) and 2) I use the file extension for frontend video player settings.

Streamlink, which is what I use for video downloads, supports downloading audio only. I've got audio-only support working locally and will create a PR for it soon. To keep things simple, I'm not creating a `mp3` file and simply keeping it in the `mp4` container, just without a video stream. This allows me to simply copy the AAC audio stream from the downloaded file without having to convert to mp3/mpeg. 

As for per-channel ffmpeg arguments, I've always pointed users to use external FFmpeg, [Tdarr](https://home.tdarr.io/), or [FileFlows](https://fileflows.com/) if they need more advanced video/audio post processing. The built-in ffmpeg arguments are really to just fix the audio issues with live streams and ensure archives are consistent. With audio only archives supported with custom ffmpeg arguments, do you still have a need for per-channel ffmpeg arguments?

**Comment by ccKep** [comment]
> With audio only archives supported with custom ffmpeg arguments, do you still have a need for per-channel ffmpeg arguments?

As long as I can set this on a per-channel basis (eg. have 3 channels recorded normally with video/hls and 1 channel audio-only) I'm totally fine with that. The actual point of the Feature Request is just to save on disk space by just keeping the audio for that channel and reduce the need to manually post-process that channels VODs.

**Comment by Zibbp** [comment]
I've pushed https://github.com/Zibbp/ganymede/pull/431 to main which adds support for archiving videos as audio only. If you want to try this out you'll need to run the `:main` image tag for both the API and frontend containers.

**Comment by ccKep** [comment]
Thanks for your work - I just switched to `:main` for the API and frontend containers, will report when I get results! (aswell as on my other open issues).

**Comment by ccKep** [comment]
Working great, thanks for your efforts!
