### ISSUE TITLE
Temporary Video not deleted after successful archive

### ISSUE THREAD

**Issue by ccKep** [Zibbp/ganymede#436]
Ganymede doesn't seem to like cleanup up after itself anymore. I've noticed this issue since last week or so.
I'm on :latest and even tried setting up the temporal container & postgres db completely from scratch, to no avail.

The Workflows all run through:

![image](https://github.com/Zibbp/ganymede/assets/8322241/4552db18-3491-4199-ab29-31477b2a39db)
![image](https://github.com/Zibbp/ganymede/assets/8322241/e0d76288-d972-427e-9f8c-9784ab23ccb9)

However the temporary file still exists:
```
ganymede@vod:/ganymede-tmp$ ls -alh /ganymede-tmp/
total 4.0G
drwxr-xr-x  4 ganymede ganymede 4.0K May 28 17:46 .
drwxr-xr-x 22 root     root     4.0K Jan 29 10:25 ..
-rw-r--r--  1 ganymede ganymede 4.0G May 28 17:45 2143448849_b769cb54-1d08-11ef-b2fe-0242ac120007-video-convert.mp4
drwxr-xr-x  8 ganymede ganymede 4.0K Dec 16 03:20 TwitchDownloader
drwx------  5 ganymede ganymede 4.0K May 25 05:26 TwitchDownloaderCLI
```

I've mounted the temp folder (which I put onto an ssd for faster conversions) inside the container (which worked flawlessly the last few months):

docker-compose.yml:
```
    volumes:
      - ./vods:/vods
      - ./logs:/logs
      - ./data:/data
      # Uncomment below to persist temp files
      - /ganymede-tmp:/tmp
```

I made sure there's no permissions issue by accessing and deleting the files from inside the ganymede-api container aswell.

**Comment by Zibbp** [comment]
I haven't noticed this on my local instance. Do you have the setting enabled to convert the resulting mp4 to HLS?

**Comment by ccKep** [comment]
Yes, I am converting to HLS. The remaining file is the ...-convert.mp4.

**Comment by Zibbp** [comment]
Pushed a fix to the `:main` image tag if you want to try it out.

**Comment by ccKep** [comment]
Reporting back after testing a few streams: Looks fine so far, thanks!
