### ISSUE TITLE
VOD Folder Name

### ISSUE THREAD

**Issue by Aerglonus** [Zibbp/ganymede#44]
The current folder path for the VoD and chat inside the streamer folder is named with a generated ID (Ganymede ID) which makes it difficult to the user to know which folder contains the VoD of X day without using the GUI (navigating through OS file explorer), using a folder structure like this, does it affect the database / VoD existence validation? 
Options:

1 - Streamer _Name
     └── 2022/10/02/(DATE_THE_STREAM_HAPPEND)
         └── ID_NAMED_FOLDER/
           ├── File1
           ├── File2
           ├── File3
           └── File4

2 - Streamer_Name
     └── 2022/10/02/(DATE_THE_STREAM_HAPPEND)
        ├── File1
        ├── File2
        ├── File3
        └── File4

**Comment by Zibbp** [comment]
Hi,
Changing the naming schema would require many fundamental application and database changes and I have no plan to do so. There are ways of viewing the date of folders in linux using `ls -lah` or use an application such as [filebrowser](https://github.com/filebrowser/filebrowser).

**Comment by Zibbp** [comment]
@Aerglonus 
Hi,
I revisited this and I have implemented a "storage templating" feature in the latest [v1.1.7 release](https://github.com/Zibbp/ganymede/releases/tag/v1.1.7). This allows the customization of how folders and files are named, including the date streamed, type, title, id, and more. Hope this helps!
