### ISSUE TITLE
Temporal container errors

### ISSUE THREAD

**Issue by Zibbp** [Zibbp/ganymede#441]
## If you are reading this you need to perform the below instructions!

If your `ganymede-temporal` container has recently updated (pulling in the newest temporal image) you will encounter errors when starting the container. If  To resolve this follow these instructions.

1. **Ensure an archive is not active**
2. Bring down the temporal container `docker compose down ganymede-temporal`
3. Perform these modifications to the compose file

```diff
  ganymede-temporal:
-   image: temporalio/auto-setup:1
+   image: temporalio/auto-setup:1.23
    container_name: ganymede-temporal
    depends_on:
      - ganymede-db
    environment:
-     - DB=postgresql # this tells temporal to use postgres (not the db name)
+     - DB=postgres12 # this tells temporal to use postgres (not the db name)
      - DB_PORT=5432
      - POSTGRES_USER=ganymede
      - POSTGRES_PWD=PASSWORD
```

4. Pull the image `docker compose pull ganymede-temporal`
5. Bring temporal up `docker compose up -d ganymede-temporal`

**Comment by ccKep** [comment]
For some reason using `DB=postgres12` did not work for me:
config validation error: persistence config: missing config for datastore "default".

- I made sure I am on 1.23 (even tried 1.22)
- I tried dropping the `temporal` and `temporal_visibility` databases from postgres to ensure a clean slate

After switching back to `DB=postgres` (using `1.23` of `temporalio/auto-setup`) it started working again.

**Comment by c-hri-s** [comment]
CHanges worked fine for me (DB=postgres12) - thanks
