### ISSUE TITLE
Importing Existing VODs and Channels in Fresh Install

### ISSUE THREAD

**Issue by FirestrikeX** [Zibbp/ganymede#446]
Using the default docker compose path for all VODs and VOD data (/path/to/vod/storage). From a fresh installation is there any way to quickly import all channels/vod information back in Ganymede?

**Comment by Zibbp** [comment]
Is the old database still running some where, or do you have a backup of it? There is no way to "scan" directories to re-import.

**Comment by FirestrikeX** [comment]
Got it, I was just curious because I seem to be getting this error less from a fresh install than an old one but it could just be random. Thanks!

https://github.com/Zibbp/ganymede/issues/356
