### ISSUE TITLE
Delete box appears behind 'processing' videos

### ISSUE THREAD

**Issue by c-hri-s** [Zibbp/ganymede#459]
Appreciate this is probably unlikely to be a regular issue for people, but if you try to delete a stream on a channel which still has videos processing then 'delete' dialog appears behind the 'processing' boxes which obscure it:

![image](https://github.com/Zibbp/ganymede/assets/13216128/32dc9129-49a4-4c60-98ab-b5306bc6f40c)

**Comment by Zibbp** [comment]
Will be resolved when v3 is out. Beta testing is available: https://github.com/Zibbp/ganymede/issues/474.
