### ISSUE TITLE
v3 ganymede-api: error: exec failed: exec format error

### ISSUE THREAD

**Issue by CrushTub3** [Zibbp/ganymede#483]
Hello,

i reinstalled freshly today to upgrade to v3.
After installation the ganymede-api container throws following error:
`error: exec failed: exec format error`

As mentiond in https://github.com/Zibbp/ganymede/issues/474 i also tried to use the :dev tag and got the same error as jayjay181818 before.

In tags `:latest` and `:dev` the image is arm64 as i use an Raspberry Pi. Maybe this is only a problem on arm64 devices?

Log from ganymede-api with tag :latest
```error: exec failed: exec format error```

Log from ganymede-api with tag :dev
```error: exec failed: exec format error

usermod: no changes

-------------------------------------

User uid:    911

User gid:    911

-------------------------------------
```

**Comment by jayjay181818** [comment]
I tried completely renaming the directories on my orange pi 5 plus, deleting the compose folders etc using the latest image... but got the same issue. Ive been trying to troubleshoot with chatgpt and i did spot a difference between my mac and my pi which chatgpt suggested...
My pi when i run "uname -m" it's aarch64, but on my mac it's arm64. Chatgpt advised that if an image is arm64 it should work with aarch64 and they are interchangeable.. But i know chatgpt doesn't get everything right. But maybe this is a sign?

**Comment by Zibbp** [comment]
I noticed some other issues with how the arm64 variant is built. Can you guys try again using the latest build of the `:dev` image? It should be fully functional now.

**Comment by jayjay181818** [comment]
Stopped the containers and updated the stack from :latest to :dev again on my Orange Pi 5 plus... It's up and running from what I see. Testing out on an old vod and it seems to be working! Will update tomorrow if it fully completes the task but I imagine it will! 
Hopefully, the change you did to :dev can be easily implemented to :latest as I imagine it will be the more stable tag. 
![CleanShot 2024-08-16 at 00 49 28@2x](https://github.com/user-attachments/assets/dbd34ac5-6585-49e2-bdbe-2edee98041d0)

**Comment by jayjay181818** [comment]
Update on the above, the VOD i manually downloaded was completed successfully, chat n all. Working fine :)

**Comment by CrushTub3** [comment]
Now also works for me with the current :dev image.

**Comment by Zibbp** [comment]
Awesome. I'll push out a release sometime this weekend so it'll be available with the `:latest` tag.

**Comment by jayjay181818** [comment]
Hmm, not sure if it's just me. But I stopped my containers, removed the :latest image and swapped over to :latest I was still getting the same error as before.  Swapping back to :dev got it back up and running however

**Comment by Zibbp** [comment]
I didn't get around to publishing a new release. It should be available now.
