### ISSUE TITLE
v3 frontend login issues

### ISSUE THREAD

**Issue by russelg** [Zibbp/ganymede#490]
Discovered a couple issues on my production instance:

### Logging out doesn't work
You get redirected to the login page, but the cookies are still kept. So upon refreshing the page, I still am logged in.
Clearing the cookies manually works.

### Unauthenticated users cannot view VODs
The VOD page makes a request for your playback position, which fails with a 401 if you aren't logged in. When this happens, it doesn't seem like the video player initialises.
It also then tries to refresh the token, which doesn't work because in this case there is no token cookie set. (fails with `http: named cookie not present`)

This playback request also occurs on the homepage for each of the recently archived VODs, which means you get spammed with `Invalid access token` error toasters. There doesn't seem to be a limit as to how many times this request gets reattempted, so it's an infinite loop of requesting playback then trying to refresh auth token.

**Comment by Zibbp** [comment]
The [v3.0.1](https://github.com/Zibbp/ganymede-frontend/releases/tag/v3.0.1) release of the frontend fixes all of this.
