### ISSUE TITLE
ConvertTwitchLiveChatToVodChat fails

### ISSUE THREAD

**Issue by fstarkenberg** [Zibbp/ganymede#50]
Since a couple of days back converting a live chat to vod chat fails. It might be Twitch that changed something in their backend.

I get:
```
{"level":"error","error":"failed to unmarshal chat file: json: cannot unmarshal string into Go struct field .author.badges.version of type int","time":"2022-10-28T20:07:38Z","message":"error converting chat"}
```

When looking at the chat file I've found some messages that look like this:
```json
    {
        "action_type": "text_message",
        "author": {
            "badges": [
                {
                    "click_action": "none",
                    "click_url": "",
                    "description": "Predicted Outcome One",
                    "icons": [
                        {
                            "height": 18,
                            "id": "18x18",
                            "url": "https://static-cdn.jtvnw.net/badges/v1/e33d8b46-f63b-4e67-996d-4a7dcec0ad33/1",
                            "width": 18
                        },
                        {
                            "height": 36,
                            "id": "36x36",
                            "url": "https://static-cdn.jtvnw.net/badges/v1/e33d8b46-f63b-4e67-996d-4a7dcec0ad33/2",
                            "width": 36
                        },
                        {
                            "height": 72,
                            "id": "72x72",
                            "url": "https://static-cdn.jtvnw.net/badges/v1/e33d8b46-f63b-4e67-996d-4a7dcec0ad33/3",
                            "width": 72
                        }
                    ],
                    "id": "e33d8b46-f63b-4e67-996d-4a7dcec0ad33",
                    "name": "predictions",
                    "title": "Predicted Blue (1)",
                    "version": "blue-1"
                }
            ],
            "display_name": "richbadatgame",
            "id": "255380908",
            "is_moderator": false,
            "is_subscriber": false,
            "is_turbo": false,
            "name": "richbadatgame"
        },
        "channel_id": "689331234",
        "client_nonce": "714c533b68bf42efed53338bb1ac8c58",
        "colour": "",
        "flags": "",
        "is_first_message": false,
        "message": "I'm still 20k channel points in the hole",
        "message_id": "b20311ed-be6f-4848-9d52-976bdec6e7f1",
        "message_type": "text_message",
        "returning_chatter": "0",
        "timestamp": 1666976726849000,
        "user_type": ""
    },
```

So ` .author.badges.version` seems to be a string in some cases. I replaced all those instances with an integer and the script ran correctly.

Big thanks for this awesome application by the way.

**Comment by Zibbp** [comment]
Hi,
Are you running the `:master` tag or `:latest`? 

[TwitchDownloader](https://github.com/lay295/TwitchDownloader) recently published an update changing some fields which were changed in the Twitch Chat API. In the master branch I've been making modifications to support the updates. I believe I've worked them all out, just waiting for another TwitchDownloader version to get pushed with a CLI fix. These changes break backwards compatibility with previous version of live chats being converted to "vod" chats because of various field changes.

If you're running `:latest` tag let me know as I will push out the current working master branch to a release which should fix everything.

**Comment by fstarkenberg** [comment]
Ah I should have checked the latest commits before making this issue.
I am running `:v1.0.5` but will change to `:latest`. 

Thanks!

**Comment by Zibbp** [comment]
`v1.0.5` == `latest` which is the latest "production" release. Did not know this was happening at the `latest` release. I will have to take a look further into the issue.

**Comment by fstarkenberg** [comment]
Ok I saw this change https://github.com/Zibbp/ganymede/blob/8a824159aeba90cb458c6a75d57a9c5a4017c591/internal/utils/chat.go#L323
but it's still an int here: https://github.com/Zibbp/ganymede/blob/8a824159aeba90cb458c6a75d57a9c5a4017c591/internal/utils/chat.go#L92

But I'm new to Golang and don't have a test environment for it right now so I might be chasing the wrong thing.

**Comment by Zibbp** [comment]
That might be the issue. I'm looking at past live chats (and recent) and all the badge versions are `int`. 
```json
"badges": [
                {
                    "click_action": "none",
                    "click_url": "",
                    "description": "Broadcaster",
                    "icons": [
                        {
                            "height": 18,
                            "id": "18x18",
                            "url": "https://static-cdn.jtvnw.net/badges/v1/5527c58c-fb7d-422d-b71b-f309dcb85cc1/1",
                            "width": 18
                        },
                        {
                            "height": 36,
                            "id": "36x36",
                            "url": "https://static-cdn.jtvnw.net/badges/v1/5527c58c-fb7d-422d-b71b-f309dcb85cc1/2",
                            "width": 36
                        },
                        {
                            "height": 72,
                            "id": "72x72",
                            "url": "https://static-cdn.jtvnw.net/badges/v1/5527c58c-fb7d-422d-b71b-f309dcb85cc1/3",
                            "width": 72
                        }
                    ],
                    "id": "5527c58c-fb7d-422d-b71b-f309dcb85cc1",
                    "name": "broadcaster",
                    "title": "Broadcaster",
                    "version": 1
                },
```
Yours above is a string, at least for the prediction badge. Would you be willing to send me the live chat file so I can do some debugging? Either upload here or email works. If possible, the VOD ID will also help as I can look at the chat.

**Comment by fstarkenberg** [comment]
Sure thing.

- Channel: Nextlander
- Title: Patron's Choice for October 2022...
- Date: 2022/10/28
- Ext ID: 47379076733
- ID: 03ba5bae-56e2-11ed-b0be-0242ac130002
- File: [47379076733_03ba5bae-56e2-11ed-b0be-0242ac130002-live-chat.txt](https://github.com/Zibbp/ganymede/files/9893797/47379076733_03ba5bae-56e2-11ed-b0be-0242ac130002-live-chat.txt)
(Renamed from .json to .txt for Github to accept it.

The VOD/Archive ID on Twitch is `1636863860`

**Comment by Zibbp** [comment]
Fixed the issue by allowing int and string to be unmarshalled from the live chat json https://github.com/Zibbp/ganymede/commit/a1c0aa21a9ed5422ce3bea5e634e16d3caa9326e.

While attempting to render out the chat I found another issue regarding the emotes. Some specific emotes are returning a 404 thus crashing the chat render. From another live chat this is one of the emotes causing the issue.

Name: `jokrdKEKW`
Live Chat Emoticon ID: `63855`
TwitchDownloader Emoticon ID: `emotesv2_1478ef3d8944490dbbfc35c963d63855`

I will have to take a further look into why this is returning a failure, and the difference between the two download methods.

**Comment by Zibbp** [comment]
I believe I found the issue with the emotes. Twitch's new `.gif` emotes are using a different `emoticon_id` schema (`emotesv2_b17be47a433b4896a6e086dbe903da09` for example) which [chat-downloader](https://github.com/xenova/chat-downloader) was not properly parsing. There is an open pull request that fixes that issue in the repository but it hasn't been merged.

I created a fork of chat-downloader and implemented the fix https://github.com/Zibbp/chat-downloader.

I'm in the process of testing this to see if it resolves the issue.

**Comment by Zibbp** [comment]
I just released [v1.0.6](https://github.com/Zibbp/ganymede/releases/tag/v1.0.6) with all the updates so far. Try pulling down the latest container and let me know if you experience any issues.

**Comment by fstarkenberg** [comment]
Awesome, big thanks!!

**Comment by Zibbp** [comment]
Release seemed v1.0.6 seemed to have fixed all the issues. Closing.
