### ISSUE TITLE
ganymede-frontend Container Won't Start Due to Error

### ISSUE THREAD

**Issue by taylor1021** [Zibbp/ganymede#514]
I followed the guide to upgrade my instance from v2.2.0 to v3.0.1. When I start the containers via `docker compose up -d`, everything starts except for the ganymede-frontend container, which fails with this error:

Error response from daemon: unable to find user nextjs: no matching entries in passwd file

**Comment by Zibbp** [comment]
What frontend image tag are you using and this is x86 or ARM?

**Comment by taylor1021** [comment]
I'm using `ghcr.io/zibbp/ganymede-frontend:3.0.1` and this is x86.

**Comment by taylor1021** [comment]
I've resolved this, so if there's nothing more you want to investigate, this can be closed. Thanks for looking into this.

Here's what I did:
- I downgraded the frontend and API images to 3.0.0
- The frontend container no longer failed with the nextjs error, but it would immediately exit with error 139
- I stopped all containers and removed the 3.0.0 and 3.0.1 images for both the frontend and API
- I updated the compose file and set the frontend and API images back to 3.0.1
- Upon pulling the images and starting the containers, everything just worked

**Comment by Zibbp** [comment]
That's odd and I don't have a good answer to that. The frontend container doesn't have any migrations or anything of the like so nothing to rollback and fix. Glad you were able to get it sorted out though.
