### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by CappiSteijns** [Zibbp/ganymede#515]
Hi,

I was wondering if there was a better solution to convert a video so that it won't be such a strain on my cpu. My cpu isn't the best it is a Intel i3-10100.

I played around with the Video Convert FFmpeg Args.  Right now it is using: "-c:v copy -c:a copy". Is there a better alternative to speed the conversion up?

For example this vod:
![Screenshot_20240928_095701_Firefox.jpg](https://github.com/user-attachments/assets/d25d1a6e-e052-47b0-baf0-54211b5f20a5)

![Screenshot_20240928_095747_Firefox.jpg](https://github.com/user-attachments/assets/984c4c1a-0ae2-49f9-b0ce-c08b65069a2e)

The VOD is ~6 hours. But the conversion is already taking longer than that:

![Screenshot_20240928_095928_Firefox.jpg](https://github.com/user-attachments/assets/b35780d0-e54d-43b1-a4c5-5d2ad149e70a)

![Screenshot_20240928_095953_Firefox.jpg](https://github.com/user-attachments/assets/a165c12e-499a-4aad-af2c-be8450df0116)

Thank you in advanced

**Comment by Zibbp** [comment]
The config wasn't getting re-loaded properly when the worker fetched a variable. I just pushed a commit that will fix the need for restarting the container when changing a setting.
