### ISSUE TITLE
OpenID Connect/SSO login support

### ISSUE THREAD

**Issue by TheBinaryLoop** [Zibbp/ganymede#52]
Support login via something like authentik.

**Comment by TheBinaryLoop** [comment]
I would be willing to pay some money to get this feature implemented. Can you start something like gitpay on this project?

**Comment by Zibbp** [comment]
I have no plan to implement paying for a feature. I will take a look at implementing SSO/OIDC support, do note that it may be awhile.

**Comment by Zibbp** [comment]
Not too familiar with OIDC. Should the Ganymede roles still be configured within Ganymede, or have them populated through the OIDC/Oauth provider using a group or custom scope?

**Comment by Zibbp** [comment]
Current plan is to default to the "local" login (username/password) and still create the initial admin user. If a user decides to setup Oauth they need to fill in the necessary environment variables. Once that user is authenticated via Oauth they can use the local admin account to set their Oauth account as admin. Then delete the local admin account if they want to.

**Comment by TheBinaryLoop** [comment]
> Not too familiar with OIDC. Should the Ganymede roles still be configured within Ganymede, or have them populated through the OIDC/Oauth provider using a group or custom scope?

I think it would be the cleanest if the roles are pulled from the oidc group scope.

**Comment by TheBinaryLoop** [comment]
> Current plan is to default to the "local" login (username/password) and still create the initial admin user. If a user decides to setup Oauth they need to fill in the necessary environment variables. Once that user is authenticated via Oauth they can use the local admin account to set their Oauth account as admin. Then delete the local admin account if they want to.

Sounds like a good flow. This should be safe enough to prevent accidental lockouts. Maybe consider including an option to make the oidc login the default with a url parameter to skip oidc and go to the normal auth.

**Comment by Zibbp** [comment]
> I think it would be the cleanest if the roles are pulled from the oidc group scope.

I could check the groups on initial login using the group scope and fallback to a default of "user". Specific groups would need to be created and assigned such as `ganymede-admin` or `ganymede-user`. Not sure if this is the best way though.

> Maybe consider including an option to make the oidc login the default with a url parameter to skip oidc and go to the normal auth.

I'm planning on adding a "Sign with SSO" or "Sign in with OAuth" button on the login page. Both the button and normal username/password will be visible at the same time, if this is what you meant.

**Comment by TheBinaryLoop** [comment]
> I could check the groups on initial login using the group scope and fallback to a default of "user". Specific groups would need to be created and assigned such as `ganymede-admin` or `ganymede-user`. Not sure if this is the best way though.

Sounds good but maybe let the user create the mapping of the external oidc groups to the internal groups.

> I'm planning on adding a "Sign with SSO" or "Sign in with OAuth" button on the login page. Both the button and normal username/password will be visible at the same time, if this is what you meant.

I meant not even displaying the normal login screen when oidc is set as the default. To display the normal login page, the user needs to set a url-parameter like skip_oidc=1. This would give the user a more seamless feel. If the oidc login method is not the default, then maybe display the normal login page with the "Sign in with SSO" button like you mentioned.

**Comment by Zibbp** [comment]
The very basics are working. Still need to refine and implement refreshing the access tokens. Authentik has a bug that uses the refresh token's expiration time for the access token, resulting in some very long duration access tokens. Author fixed it recently in https://github.com/goauthentik/authentik/commit/3306003f0e0ac350eaecf3ba3584fcf6c6f4a4d1.

UI elements are temporary for testing.

https://user-images.githubusercontent.com/21207065/201229205-1136a005-a812-4593-882b-5a800b958d60.mp4

I'll hopefully push out a dev release early next week to test the functionality.

**Comment by Zibbp** [comment]
I just merged https://github.com/Zibbp/ganymede/pull/53 into master which adds SSO / OAuth support. This will need some rigorous testing before being pushed out in a release. If you would like to help test you can do so by doing the following.


1. Create a new directory for this test setup, or use a new VM.
2. Grab a copy of the [docker-compose.yml](https://github.com/Zibbp/ganymede/blob/master/docker-compose.yml).
3. If on the same VM as your production setup, edit the volume paths to ensure this test setup does not point to any production volumes.
4. Edit the API and Frontend image tags from `:latest` to `:master`.
5. If on the same VM as your production setup, change the container names as to not conflict.
6. Bring the stack up to initialize the config `docker compose up`.
7. Visit the work in progress [SSO/OAuth docs](https://github.com/Zibbp/ganymede/wiki/SSO---OpenID-Connect) to get started.

**Comment by Zibbp** [comment]
Logging out functionality still needs to be added. Figured I'd push what I have now for testing.

**Comment by TheBinaryLoop** [comment]
I'm going so set up a testing instance now. Gonna report back if I find something interesting

**Comment by TheBinaryLoop** [comment]
Works great. Only missing an option to disable/skip the normal login page by default so that it jumps straight to the SSO provider 👍 Great work on your side man. Didn't expect you to be that fast regarding a community request. Thanks a lot. This makes the user experience so much better for me

**Comment by Zibbp** [comment]
The frontend currently does not know whether SSO is being used. I can add an environment variable to the frontend that will force the "login" button at the top right to take the user directly to the SSO provider. Local authentication can still be achieved by manually visiting the `/login` route.

**Comment by Zibbp** [comment]
Version [v1.0.8](https://github.com/Zibbp/ganymede/releases/tag/v1.0.8) has been released. This release includes the SSO addition. For now, I'm leaving the frontend as is as I'm tinkering with the idea of re-writing the frontend in React. More information can be found here https://github.com/Zibbp/ganymede/issues/54.

I'm going to leave this issue open for a few days incase any issues arise with SSO.

**Comment by Zibbp** [comment]
Hi, release [v1.1.0](https://github.com/Zibbp/ganymede/issues/63) was just pushed out. In this release includes a new frontend that allows for more customization with SSO. Two new environment variables have been added, `SHOW_SSO_LOGIN_BUTTON` and `FORCE_SSO_AUTH`. For more information regarding these please visit https://github.com/Zibbp/ganymede/issues/63 or take a look at the updated readme.
