### ISSUE TITLE
"undefined" 404 errors on multiple elements

### ISSUE THREAD

**Issue by wagyus** [Zibbp/ganymede#533]
I've done a fresh install on a new machine recently. I can login fine with the default admin, logs seem to show no issues in Docker, but when I add a new channel and update the profile picture, Chrome console shows

 `profile.png:1 
 GET http://10.0.0.236:4801/undefined/data/videos/vargskelethor/profile.png 404 (Not Found)`

Notably, the 'undefined' value seems to be causing the issue because the API does go and fetch the image and VODs just fine from Twitch.

```
SSH Console
[10.0.0.95] USER@HOST:/mnt/media/Twitch/videos/vargskelethor $ file profile.png 
profile.png: PNG image data, 300 x 300, 8-bit/color RGB, non-interlaced
```

I am unable to view VODs since this issue is present for me. Ganymede downloads videos and chat just fine, and places them in the correct locations on my server. Attached is my `docker-compose.yml`
[docker-compose.txt](https://github.com/user-attachments/files/17693131/docker-compose.txt)

**Comment by Zibbp** [comment]
The `CDN_URL` environment variable for the frontend container still needs to be set even if you're not using Nginx. In your setup it should be
```
- CDN_URL=http://10.0.0.236:4800
```
as you're letting the API serve the static files.

**Comment by Zibbp** [comment]
I'll try to think of some better wording, or if you have any please open a PR!
