### ISSUE TITLE
Cannot disable auto migration of paths

### ISSUE THREAD

**Issue by Entrivax** [Zibbp/ganymede#536]
I'm currently facing an issue, I would like to change the environment variable `VIDEOS_DIR` to another path because my drive currently hosting my VODs is full, so I mounted the folder with my current VODs to the same old path `/data/videos` and mounted the second drive to `/data/videos2`, then I want the new VODs to be downloaded to that new path, so I changed the variable to `VIDEOS_DIR=/data/videos2`.
The problem is that the migration is ran at startup and cannot be skipped https://github.com/Zibbp/ganymede/blob/528562bf5c265c7d487eddbb8fe865a2f14eae69/internal/server/server.go#L80-L87

It could be very nice to be able to skip this step in a case like this where multiple drives are used and the non-uniformity of the paths is intentional. Maybe by adding a new environment variable to skip this auto migration?
Right now, if I try to do this, all the paths are broken, because the previous files are not on the new drive.

**Comment by Zibbp** [comment]
Thanks for the PR. I never envisioned using multiple drives like this.

**Comment by Entrivax** [comment]
Yeah, I already completely filled my 18TB disk so I had to add a new one!
