### ISSUE TITLE
Feature Request: Option to (re-)generate new thumbnails after recording

### ISSUE THREAD

**Issue by ccKep** [Zibbp/ganymede#542]
Most channels I'm viewing have a starting screen at the start of the stream (5m, 10m, sometimes up to 20m).

It'd be nice to have an option (maybe even channel specific) to regenerate thumbnails after the stream recording is finished (basically the same as the button "Regenerate thumbnail" already does).

As an added bonus: Maybe a "minimum time" setting would be nice so I could set it to "10 minutes" and the functionality would only consider the time window [00:10:00;Stream End] (if the stream is atleast the specified duration, if it's not: ignore the setting).

**Comment by Zibbp** [comment]
A task runs 10 minutes after the initial thumbnail download completes for livestreams to re-download the thumbnails from Twitch again, so the logic (maybe not the same as you proposed but accomplishes it) for this is already running. 

https://github.com/Zibbp/ganymede/blob/0a350cb1371506a02ab76c89b86f927375420452/internal/tasks/common.go#L358-L366

I'm guessing as it's only 10 minutes that it's still catching the stream's starting screen. 

If I made the time to re-download thumbnails configurable, would that work? Or maybe using the downloaded video is better and just randomly pick a time each archive to grab a thumbnail (excluding the first 20? and last 20? minutes)?

**Comment by ccKep** [comment]
Making that time configurable would work perfectly fine, yes!

**Comment by Zibbp** [comment]
Instead of making it configurable I've made the regenerate thumbnail task run after the live stream archive finishes.
