### ISSUE TITLE
Various API 404 Issues on Synology

### ISSUE THREAD

**Issue by Crisped2225** [Zibbp/ganymede#552]
Hi, I've spent a few hours trying to get this working as a synology docker newbie, and I'm stumped! 

Managed to get everything loaded/mounted, but the home page does not allow me to login, or create a new user. 

It also says "Request Failed" a few times when loading the home page. Not sure which part of the info is helpful, but the some of the 404 request includes:

HTTP API error 
Object { stack: "Q@http://192.168.51.199:4801/_next/static/chunks/pages/_app-ec1726ae468c8573.js:30:183392\neI@http://192.168.51.199:4801/_next/static/chunks/pages/_app-ec1726ae468c8573.js:30:194282\ny@http://192.168.51.199:4801/_next/static/chunks/pages/_app-ec1726ae468c8573.js:30:199120\nEventHandlerNonNull*87066/eV</<@http://192.168.51.199:4801/_next/static/chunks/pages/_app-ec1726ae468c8573.js:30:199375\n87066/eV<@http://192.168.51.199:4801/_next/static/chunks/pages/_app-ec1726ae468c8573.js:30:198723\nto@http://192.168.51.199:4801/_next/static/chunks/pages/_app-ec1726ae468c8573.js:30:205686\n_request@http://192.168.51.199:4801/_next/static/chunks/pages/_app-ec1726ae468c8573.js:30:208476\nrequest@http://192.168.51.199:4801/_next/static/chunks/pages/_app-ec1726ae468c8573.js:30:207027\n87066/d/<@http://192.168.51.199:4801/_next/static/chunks/pages/_app-ec1726ae468c8573.js:30:177754\nr@http://192.168.51.199:4801/_next/static/chunks/5262-9ef227e0ff206064.js:1:9371\nqueryFn@http://192.168.51.199:4801/_next/static/chunks/pages/index-a34302629c9c62e2.js:1:5918\nfetchFn@http://192.168.51.199:4801/_next/static/chunks/pages/_app-ec1726ae468c8573.js:30:169810\nb@http://192.168.51.199:4801/_next/static/chunks/pages/_app-ec1726ae468c8573.js:30:173342\n72008/c/b/</<@http://192.168.51.199:4801/_next/static/chunks/pages/_app-ec1726ae468c8573.js:30:173661\npromise callback*72008/c/b/<@http://192.168.51.199:4801/_next/static/chunks/pages/_app-ec1726ae468c8573.js:30:173644\npromise callback*b@http://192.168.51.199:4801/_next/static/chunks/pages/_app-ec1726ae468c8573.js:30:173403\nstart@http://192.168.51.199:4801/_next/static/chunks/pages/_app-ec1726ae468c8573.js:30:173825\nfetch@http://192.168.51.199:4801/_next/static/chunks/pages/_app-ec1726ae468c8573.js:30:170897\n#f@http://192.168.51.199:4801/_next/static/chunks/777-4e392a95cd4ebf0b.js:1:2602\nfetch@http://192.168.51.199:4801/_next/static/chunks/777-4e392a95cd4ebf0b.js:1:2489\nrefetch@http://192.168.51.199:4801/_next/static/chunks/777-4e392a95cd4ebf0b.js:1:2277\nonFocus@http://192.168.51.199:4801/_next/static/chunks/pages/_app-ec1726ae468c8573.js:30:168447\n30986/onFocus/</<@http://192.168.51.199:4801/_next/static/chunks/pages/_app-ec1726ae468c8573.js:9:19099\n30986/onFocus/<@http://192.168.51.199:4801/_next/static/chunks/pages/_app-ec1726ae468c8573.js:9:19085\nbatch@http://192.168.51.199:4801/_next/static/chunks/pages/_app-ec1726ae468c8573.js:30:165580\nonFocus@http://192.168.51.199:4801/_next/static/chunks/pages/_app-ec1726ae468c8573.js:9:19060\n@http://192.168.51.199:4801/_next/static/chunks/pages/_app-ec1726ae468c8573.js:9:20876\nasync*66474/onFocus/<@http://192.168.51.199:4801/_next/static/chunks/pages/_app-ec1726ae468c8573.js:30:162036\nonFocus@http://192.168.51.199:4801/_next/static/chunks/pages/_app-ec1726ae468c8573.js:30:162023\n@http://192.168.51.199:4801/_next/static/chunks/pages/_app-ec1726ae468c8573.js:30:161909\nt@http://192.168.51.199:4801/_next/static/chunks/pages/_app-ec1726ae468c8573.js:30:161572\n", message: "Request failed with status code 404", name: "AxiosError", code: "ERR_BAD_REQUEST", config: {…}, request: XMLHttpRequest, response: {…}, status: 404 }
​
code: "ERR_BAD_REQUEST"
​
config: Object { timeout: 0, xsrfCookieName: "XSRF-TOKEN", xsrfHeaderName: "X-XSRF-TOKEN", … }
​
message: "Request failed with status code 404"
​
name: "AxiosError"
​
request: XMLHttpRequest { readyState: 4, timeout: 0, withCredentials: false, … }

Then when trying the default admin/ganymede login info, the 404 is:

"http://192.168.51.199:4801/192.168.51.199:4800/api/v1/auth/register"

4801 is the webpage location, 4800 is the api. When I try to go to :4800 manually, it says "Ganymede API" in the browser

Is this an auth issue with twitch? What OAuth Redirect URL should be entered? I have it set to https://localhost

Here is my compose file, the synology logs dont seem to have anything useful or obvious errors

[docker-compose.txt](https://github.com/user-attachments/files/18233999/docker-compose.txt)

I'm probably doing something wrong, but pointers would be appreciated!

**Comment by Zibbp** [comment]
Hi,
I have a big v4.0.0 release coming out tonight or tomorrow. In the new release will be improvements to setting up Ganymede. I would wait until that is released and try the new version, it'll be a lot easier.

**Comment by Zibbp** [comment]
[v4.0.0](https://github.com/Zibbp/ganymede/releases/tag/v4.0.0) has been released if you want to try that. I would start with a fresh `docker-compose.yml` from the repository and copy over your customizations.

**Comment by Crisped2225** [comment]
Does work with 4.0 now
