### ISSUE TITLE
v4 - watched channels, Max Video Age not saving

### ISSUE THREAD

**Issue by janolehuebner** [Zibbp/ganymede#554]
When I edit watched channels, Advanced -> Max Video Age (days) defaults to 7. 
No matter which value I enter, if I click save and reopen the settings the value is back to 7.![image](https://github.com/user-attachments/assets/65796061-b8ba-481d-9d73-c38320d0ad00)

**Comment by Zibbp** [comment]
Thanks for the report. The fix should be available using the `:dev` image tag shortly. I'll push a new release later today or tomorrow.
