### ISSUE TITLE
Unable to change max video age?

### ISSUE THREAD

**Issue by jayjay181818** [Zibbp/ganymede#558]
Have to say, stellar release again! 
I got my three Ganymede instances updated and love the new functionality; it also seems a lot more responsive!
Imagine this is simply a bug, but I can't seem to increase the max video age from 7 days. I never used to archive clips, but with the introduction of the new function to be able to see clips taken within a vod, I wanted to archive clips I hadn't before.

I imagine this is a bug with the new release? I've tried restarting the dockers and trying again, but no joy.  

Great work though @Zibbp and what a great Christmas gift! 🎄

**Comment by Zibbp** [comment]
Thanks!
Yes that is a bug, it's been fixed in https://github.com/Zibbp/ganymede/pull/555 and is available using the `:dev` image. I'm planning to publish a new release in the next couple of days.
