### ISSUE TITLE
invalid tar header on Synology

### ISSUE THREAD

**Issue by Crisped2225** [Zibbp/ganymede#562]
Trying to install v4, and I am getting an error on project creation. The db does deploy properly if I remove the ganymede section from the compose file

....
de0d587eae33 Download Complete
failed to register layer: ApplyLayer exit status 1 stdout:  stderr: archive/tar: invalid tar header

**Comment by janolehuebner** [comment]
I have the same. I think it's a docker bug though. As a workaround I built the image on the nas myself

**Comment by Zibbp** [comment]
Interesting. I changed the image to use zstd compression for v4 but I'm guessing Synology doesn't support that? I reverted that change so it should use the standard compression now, I think gzip? Can you try the `:dev` image?

**Comment by janolehuebner** [comment]
yepp... works now

**Comment by Crisped2225** [comment]
I still have the same issue on the latest build (12-27 @ 1:45EST)

I'm not sure how exactly to use the compose file/etc with this dev image, using docker pull just loads it in the image section of container manager, unsure how to actually use it then.

Instead, at the main page I'm just clicking the code button > download zip to get the latest, is that wrong?

**Comment by janolehuebner** [comment]
@Crisped2225 you create a new project in container manager and paste in the compose yaml or load it from a file then you change the `image: ghcr.io/zibbp/ganymede:latest` part to `image: ghcr.io/zibbp/ganymede:dev`
It should then pull the image with the dev tag

**Comment by Crisped2225** [comment]
@janolehuebner Ah that makes sense, thank you! It did run this time
