### ISSUE TITLE
Help for beginners

### ISSUE THREAD

**Issue by urkoperez16** [Zibbp/ganymede#564]
I just installed the Docker container by UnRaid, changing the initial command (with the help of ChatGPT) because the default one gives errors. I managed to start it, enter the web page and log in, but I can't start using it.

![image](https://github.com/user-attachments/assets/d64b6a6b-2f95-48f4-9c1d-9639df3ec934)

**Comment by Zibbp** [comment]
I'm not familiar with Unraid, what did you change? What credentials did you use to log in, `admin`/`ganymede`?

**Comment by urkoperez16** [comment]
OOOH THAT WAS THE PROBLEM, THANK YOU VERY MUCH.

**Comment by urkoperez16** [comment]
I'm still having problems, I want to add channels but it gives an error. 

[Screen recording 2024-12-27 12.27.28.webm](https://github.com/user-attachments/assets/e263e0bf-3518-4d26-b551-df137f2d0702)

**Comment by Zibbp** [comment]
Do you have the Twitch client ID and secret set in your compose (or Unraid's equivalent)?

**Comment by urkoperez16** [comment]
Yes, I created an application on dev.twitch.tv and set the keys (Id and Id Secret).

**Comment by Zibbp** [comment]
Can you use the `:dev` image tag and look at the logs when the container starts? I'm thinking it's something with your twitch client id and secret. When starting it should show two `twitch connection authenticated"` log messages, one for the server and one for the worker.

**Comment by urkoperez16** [comment]
It does not appear that

https://github.com/user-attachments/assets/1e0ad6c0-6956-495e-8ffe-b5046141d232

**Comment by Zibbp** [comment]
Can you post the environment variables of the container in Unraid? Be sure to blank out sensitive secrets.

**Comment by Zibbp** [comment]
The `TWITCH_CLIENT` env var needs to be `TWITCH_CLIENT_SECRET` so there is both `TWITCH_CLIENT_ID` and `TWITCH_CLIENT_SECRET`.

**Comment by urkoperez16** [comment]
I don't understand

**Comment by Zibbp** [comment]
Your environment variables are wrong.
```
-e 'TWITCH_CLIENT_ID'='XXXXXXXXXXXXXXXXXXXX'
-e 'TWITCH_CLIENT'='XXXXXXXXXXXXXXXXXXXXXX' 
```
Please reference the `docker-compose.yml` for what these should be.

**Comment by urkoperez16** [comment]
This is what I have set in the docker command, including the secret id that does not come up

![image](https://github.com/user-attachments/assets/085e8714-044f-4b03-b436-e42bcd8caf81)

**Comment by Zibbp** [comment]
I'm saying that `TWITCH_CLIENT` is **incorrect**. It is `TWITCH_CLIENT_SECRET`. Please read the README for more information. I am unable to further help as this requires you to correct the incorrect variable name.

**Comment by urkoperez16** [comment]
I have change some things and now starts with less errors. I still think I have the right variables, even when looking at README. 

![Screenshot_92](https://github.com/user-attachments/assets/81c6c52c-7262-41a8-b832-4f4772e47fc1)

**Comment by Zibbp** [comment]
If you think you have everything configured right then I would delete all the data (postgres volume and ganymede volumes) to start fresh. Then bring everything back up. I would also enable debug logging by setting the `DEBUG` environment variable to `true`.

**Comment by urkoperez16** [comment]
I have created other new folders and they are still coming out, the twitch credentials I copy and paste them as they are.

Client ID (web) - Twitch_Client_ID (docker-compose)
Client Secret (web) - Twitch_Client (docker-compose)

![Screenshot_93](https://github.com/user-attachments/assets/015d5580-a9ef-44b7-b8b7-cb30715fcb7b)

**Comment by Zibbp** [comment]
Where are you seeing "Twitch_Client" in this docker-compose file? https://github.com/Zibbp/ganymede/blob/main/docker-compose.yml It is wrong as I've stated above multiple times.

**Comment by urkoperez16** [comment]
and which is the functional docker-compose.yml?

**Comment by urkoperez16** [comment]
I HAVE SEEN WHERE MY ERROR IS IN THE DOCKER-COMPOSE (TWITCH_CLIENT - TWITCH_CLIENT_SECRET) 

THANKS FOR YOUR WORK
(And sorry)

**Comment by nwithan8** [comment]
Apologies, that was my mistake on the Unraid app template. Fix has been pushed out.
