### ISSUE TITLE
Feature request: Add a lock icon (or other visual indicator) to locked videos

### ISSUE THREAD

**Issue by clb92** [Zibbp/ganymede#567]
I have a few watched channels with a retention period set, where I'm only interested in some of the videos/streams. I plan on manually locking all the videos I want to keep. To make this easier, I would love if the locked videos had a lock icon, or any other visual indicator, so I can easily see which videos I've already locked.

I'm not familiar with your codebase yet, but I imagine this could be somewhat easily?

**Comment by mark-addams001881** [comment]
Hello, we tried to solve the issue.

This is what we did:

Added a lock icon to visually indicate locked videos in the VideoCard component. This helps users easily identify which videos they've locked for retention. The lock icon is displayed next to the watched icon, using similar styling for consistency.

You can review changes in this commit: https://github.com/mark-addams001881/Zibbp-ganymede-567/commit/f64a0df575840b1559c692ecfecb728e4302cc2d.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by Zibbp** [comment]
Good idea, I've added an icon to the card, title bar, and the admin videos table https://github.com/Zibbp/ganymede/pull/568. It should be available in a release later today.

**Comment by clb92** [comment]
Amazing, thanks!
