### ISSUE TITLE
Webhook Configurability

### ISSUE THREAD

**Issue by gnosticJade** [Zibbp/ganymede#64]
If possible, I'd like to see more configuration available to the user for webhooks. Ideally they'd be fully customizable, but I understand that it'd be difficult to design a user-friendly method. Ideally users would be able to use the exposed variables in vod.go and define the webhook's formatting on their own. As a failure state, any invalid syntax could be ignored and use a sane default, similar to the current output.

- Give the user options for what webhooks they want to use 
  - Alternatively, using different webhook for different states (ex. errors to $webhook1, successful to $webhook2)
- Add a webhook call for when stream recordings begin/a channel is detected as live. The webhooks currently implemented are archival completion and task failures.
- If user-configurable webhook output isn't something you'd like to put on the roadmap, then stream archival alerts could be changed to something more verbose; these are first-pass suggestions, but would help users identify urgency/what each alert actually is.
  - Success: `:white_check_mark: Live Stream Archived: $streamTitle` ->  `:white_check_mark: Live Stream Archived: $streamTitle by $streamer, streamed at $streamed_at`
  - Fail: `:warning: Error: Queue ID $id failed at task $step_failed.` -> `:warning: Error: Queue ID $id by $streamer failed at task $step_failed.`

Ideally some of these variables could be made accessible, if user-configuration is the route you go:
https://github.com/Zibbp/ganymede/blob/a0f6d79994fa8ec4745a781c9fae1f1f8b5ca24c/internal/vod/vod.go#L30-L49

**Comment by Zibbp** [comment]
Thinking of four notifications for now. Video archive success, live archive success, failure, and channel live. Should the "video archive success" and "live archive success" be merged into one notification? Doing so wouldn't allow for specific verbiage such as "Live Stream archived" or "VOD archived".

Planning to stick with webhooks only in Ganymede. If users want more, they can setup [Apprise](https://github.com/caronc/apprise-api) which accepts a webhook input then can push the data received out to various other providers.

Regarding the UI for this, here is a something I threw together for the "video archive success" notification.
![brave_nyE7JWrUaj](https://user-images.githubusercontent.com/21207065/203866969-73808ca0-3a58-4817-a3ec-04b4e1054234.png)

Do you think this is configurable enough?

**Comment by gnosticJade** [comment]
I think that looks great & it makes sense to leave the advanced functionality to a secondary application such as Apprise. I don't think there's any harm in having the VOD archival and livestream archival webhooks being separate - I believe that VOD archives are generally going to be invoked by a user to begin with, so it makes sense to allow the user to opt-out of getting those notifications.

One additional change that may be beneficial - either a preview with dummy data for the template _or_ a test webhook button to preview the output as-configured. I figure either of those should help cut down on any bug reports claiming their templates are behaving unexpectedly.

**Comment by Zibbp** [comment]
Hi,
I just released [v1.1.1](https://github.com/Zibbp/ganymede/releases/tag/v1.1.1) which includes the better notification support. I will leave this issue open for a few days if any issues occur with the new notifications.

**Comment by gnosticJade** [comment]
This seems to be working great - haven't run into any issues so far! I'm going to mark it as closed but if I run into any trouble with them in the future. Thanks for the quick response & work on the project!
