### ISSUE TITLE
I give in. I have nearly lost my sanity. Please help!

### ISSUE THREAD

**Issue by gavonmothma** [Zibbp/ganymede#71]
---
version: "3.9"

networks:
  default:
    driver: bridge
  ganymede:
    name: ganymede
    driver: bridge
    ipam:
      config:
        - subnet: 172.15.0.0/16 

# Keys common to some of the dependent services/apps
x-default-keys-apps: &default-keys-apps
  networks:
    - ganymede
  security_opt:
    - no-new-privileges:true
  restart: unless-stopped

services:
  ganymede-api:
    <<: *default-keys-apps
    container_name: ganymede-api
    image: ghcr.io/zibbp/ganymede:latest
    restart: unless-stopped
    environment:
      - TZ=US/Eastern # Set to your timezone
      - DB_HOST=ganymede-db
      - DB_PORT=5432
      - DB_USER=ganymede
      - DB_PASS=PASSWORD
      - DB_NAME=ganymede-prd
      - DB_SSL=disable
      - JWT_SECRET=SECRET
      - JWT_REFRESH_SECRET=SECRET
      - TWITCH_CLIENT_ID=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - TWITCH_CLIENT_SECRET=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - FRONTEND_HOST=http://192.168.254.131:4801
      # OPTIONAL
      # - OAUTH_PROVIDER_URL=
      # - OAUTH_CLIENT_ID=
      # - OAUTH_CLIENT_SECRET=
      # - OAUTH_REDIRECT_URL=http://IP:PORT/api/v1/auth/oauth/callback # Points to the API service
    volumes:
      - $DATADIR/VODS/Twitch:/vods
      - $DOCKERDIR/appdata/ganymedeapi/logs:/logs
      - $DOCKERDIR/appdata/ganymedeapi:/data
      # Uncomment below to persist temp files
      #- ./tmp:/tmp
    ports:
      - 4800:4000
  ganymede-frontend:
    <<: *default-keys-apps
    container_name: ganymede-frontend
    image: ghcr.io/zibbp/ganymede-frontend:latest
    restart: unless-stopped
    environment:
      - API_URL=http://192.168.254.131:4800 # Points to the API service
      - CDN_URL=http://192.168.254.131:4802 # Points to the CDN service
      - SHOW_SSO_LOGIN_BUTTON=true # show/hide SSO login button on login page
      - FORCE_SSO_AUTH=false # force SSO auth for all users (bypasses login page and redirects to SSO)
    ports:
      - 4801:3000
  ganymede-db:
    <<: *default-keys-apps
    container_name: ganymede-db
    image: postgres:14
    volumes:
      - $DOCKERDIR/appdata/ganymede-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=PASSWORD
      - POSTGRES_USER=ganymede
      - POSTGRES_DB=ganymede-prd
    ports:
      - 4803:5432
  ganymede-nginx:
    <<: *default-keys-apps
    container_name: ganymede-nginx
    image: nginx
    volumes:
      - $DOCKERDIR/appdata/ganymedenginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - $DATADIR/VODS/Twitch:/mnt/vods
    ports:
      - 4802:8080

I have copied and pasted the nginx.conf to the correct directory. Containers can ping each other. Links to the nginx container refuse to work. As an example, if I go to the Channel section, where the profile icons should show, they all have the default placeholder. Pulling up the console gives a 404 error, for example, for 'http://192.168.254.131:4802/vods/palmbee/profile.png' This file exists where I think it should ($DATADIR/VODS/Twitch/palmbee/profile.png). As such, I cannot view any recordings through the web interface, since they result in similar errors. They are recorded, though, and accessible through a local file browser.

My other issue is that VODs are not being fetched, only live recordings.

I have changed and checked and tried what I feel is every possible combination of everything, lol. Please help restore me to sanity.

The command
sudo docker exec ganymede-nginx ls -la /mnt/vods

lists the root directories for each streamer (palmbee, cloakzy, etc).  This is on Ubuntu 22.04 Desktop. This is part of a much larger docker-compose.yaml with 28 containers. Everything else is on a separate docker network. I have tried to keep all of the relevant information from my docker-compose.yaml to this project.

**Comment by Zibbp** [comment]
Hi,

> Pulling up the console gives a 404 error, for example, for 'http://192.168.254.131:4802/vods/palmbee/profile.png' This file exists where I think it should ($DATADIR/VODS/Twitch/palmbee/profile.png). As such, I cannot view any recordings through the web interface, since they result in similar errors. They are recorded, though, and accessible through a local file browser.

- Does the profile image URL give an Nginx 404 error?
- If you run `ls $DATADIR/VODS/Twitch` is the output a list of channel folders?
- If you exec into the Nginx container and run `cat /etc/nginx/nginx.conf` does it output the download `nginx.conf` file?
- Any errors in the Nginx container logs?
- Is there another service within that docker-compose file that is running internally on port 8080?

> My other issue is that VODs are not being fetched, only live recordings.

Is this when a channel is set to "watched" or when manually archiving a VOD when entering a ID?

**Comment by gavonmothma** [comment]
> * Does the profile image URL give an Nginx 404 error?

Yes
> * If you run `ls $DATADIR/VODS/Twitch` is the output a list of channel folders?

Yes
> * If you exec into the Nginx container and run `cat /etc/nginx/nginx.conf` does it output the download `nginx.conf` file?

Yes
> * Any errors in the Nginx container logs?

2023/01/01 17:24:17 [error] 29#29: *2 open() "/mnt/vods/palmbee/profile.png" failed (2: No such file or directory), client: 192.168.254.160, server: , request: "GET /vods/palmbee/profile.png HTTP/1.1", host: "192.168.254.131:4802"

192.168.254.160 - - [01/Jan/2023:17:24:17 +0000] "GET /vods/palmbee/profile.png HTTP/1.1" 404 188 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"

2023/01/01 17:24:18 [error] 29#29: *2 open() "/mnt/vods/favicon.ico" failed (2: No such file or directory), client: 192.168.254.160, server: , request: "GET /favicon.ico HTTP/1.1", host: "192.168.254.131:4802", referrer: "http://192.168.254.131:4802/vods/palmbee/profile.png"

192.168.254.160 - - [01/Jan/2023:17:24:18 +0000] "GET /favicon.ico HTTP/1.1" 404 188 "http://192.168.254.131:4802/vods/palmbee/profile.png" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"

2023/01/01 17:25:17 [info] 33#33: *1 client timed out (110: Connection timed out) while waiting for request, client: 192.168.254.160, server: 0.0.0.0:8080

192.168.254.160 is my desktop PC running windows.
> * Is there another service within that docker-compose file that is running internally on port 8080?
Yes, Calibre. but like I said, ganymede is on its own separate docker network. Nevertheless, I disabled calibre, but nothing changed.

> > My other issue is that VODs are not being fetched, only live recordings.
> 
> Is this when a channel is set to "watched" or when manually archiving a VOD when entering a ID?

When it's set to watched. I see that it only checks once a day, but it's been longer than that since I set this up. In an attempt to be clear, when I go to http://192.168.254.131:4801/admin/watched and edit a channel, every toggle is switched on and quality is set to Best.

**Comment by Zibbp** [comment]
> When it's set to watched. I see that it only checks once a day, but it's been longer than that since I set this up. In an attempt to be clear, when I go to http://192.168.254.131:4801/admin/watched and edit a channel, every toggle is switched on and quality is set to Best.

This could be related to having an improper timezone env variable. Instead of `- TZ=US/Eastern` it should be `- TZ=America/New_York`. You can also manually start the task under Admin > Tasks.

Regarding the Nginx issue, I have no idea. Everything looks to be right. When you run `docker exec ganymede-nginx ls -la /mnt/vods` who is the owner for the directories and profile image? root root?

**Comment by gavonmothma** [comment]
> Regarding the Nginx issue, I have no idea. Everything looks to be right. When you run `docker exec ganymede-nginx ls -la /mnt/vods` who is the owner for the directories and profile image? root root?

It was 1000 1000. I changed it to root root and that didn't help. I feel like it has to be something really dumb that I'm missing, but I'm not familiar with nginx configuration at all.

**Comment by Zibbp** [comment]
I just released [v1.1.4](https://github.com/Zibbp/ganymede/releases/tag/v1.1.4) which allows the API container to serve the static files similar to the Nginx container. It does not include the caching rules that is in the Nginx configuration, it simply serves the static files. To use it, replace the `CDN_URL` frontend environment variable with the IP and Port of the API container with /static at the end. In your setup, it would look like `CDN_URL=http://192.168.254.131:4800/static`

I'm not too familiar with Nginx and I cannot see an issue with your configuration so hopefully this helps while you continue to troubleshoot or I find something wrong. Let me know how this works.

**Comment by gavonmothma** [comment]
This works great for me. Thanks! Sorry for taking so long to reply. It's been working for me since you posted this. So I assume this is something temporary and I need to sort out my nginx issue?

**Comment by Zibbp** [comment]
You can keep using it without Nginx and using the API container to serve the static files. That is a permanent change I added. The difference between using Nginx and the API container for static files using a local deployment is negligible.
