### ISSUE TITLE
Streamlink invalid argument

### ISSUE THREAD

**Issue by Aerglonus** [Zibbp/ganymede#74]
After redeploying the container with fresh images the following error showed in failed live archive vods 

usage: streamlink [OPTIONS] [STREAM]
streamlink: error: unrecognized arguments: best,best

**Comment by Zibbp** [comment]
Hi,
Can you provide your Streamlink args found at Admin > Settings. Does this occur while downloading a video or live stream?

**Comment by Aerglonus** [comment]
--force-progress,--force,--twitch-low-latency,--twitch-disable-hosting, --twitch-api-header=Authorization=OAuth

**Comment by Zibbp** [comment]
There is a space in-between the disable hosting and api header argument. I'm going to guess that is causing the issue. Here is how it should look.
```
--force-progress,--force,--twitch-low-latency,--twitch-disable-hosting,--twitch-api-header=Authorization=OAuth 1234
```

**Comment by Aerglonus** [comment]
Indeed, that was the issue.
