### ISSUE TITLE
Unable channel page access

### ISSUE THREAD

**Issue by infuse765** [Zibbp/ganymede#77]
hello,
I use Ganymede well, but there is one problem.

If you access each channel through the channel page,
"404, This page could not be found." occurs. 
(Example: http://192.168.1.50:4801/channels/[channel_name])

All other functions, such as saving stream video files, are working normally.

I'm not sure which part is wrong.

**Comment by Zibbp** [comment]
Hi,

Have you ever been able to navigate to a channel or has it always thrown the "404 not found" error? Are you able to visit Admin > Channels and view a list of channels there?

If you can, please open the browser developer tools with Ctrl + Shift + I and click the network console tab at the top. Then navigate to a channels page and see if there are any errors and what it claims the error is. 

If all other functions are working as expected, it may be a CORS issue. The API container has an environment variable named `FRONTEND_HOST`. Is this set to `FRONTEND_HOST=http://192.168.1.50:4801`?

**Comment by Smallinger** [comment]
Hey, i have the same error, in the Admins Tab i can see all channels.
![image](https://user-images.githubusercontent.com/8080568/213914190-452de385-8c07-4aa7-97a7-4300d09aae37.png)

if i visit the normal channels tab i got in the console this error.

`GET http://*****/_next/data/I6z_cFY_GuzP-fGxF5TQv/channels/shlorox.json?channelName=shlorox 404 (Not Found)`

**Comment by Zibbp** [comment]
Hi,
Can you take a look at the frontend container logs and check if there are any logs pertaining to this issue?

**Comment by Smallinger** [comment]
its on every channel, here are the logs.

`AxiosError: connect ECONNREFUSED ***IPADDRESS***:443
    at Function.AxiosError.from (file:///app/node_modules/axios/lib/core/AxiosError.js:89:14)
    at RedirectableRequest.handleRequestError (file:///app/node_modules/axios/lib/adapters/http.js:533:25)
    at RedirectableRequest.emit (node:events:513:28)
    at ClientRequest.eventHandlers.<computed> (/app/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:494:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {

  port: 443,
  address: '***IPADDRESS***',
  syscall: 'connect',
  code: 'ECONNREFUSED',
  errno: -111,
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: null },
    validateStatus: [Function: validateStatus],
    headers: AxiosHeaders {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      'User-Agent': 'axios/1.2.2',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    baseURL: '***BACKEND URL***',
    method: 'get',
    url: '/api/v1/channel/name/shlorox',
    data: undefined
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError],
      socket: [Function: handleRequestSocket]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: Infinity,
      protocol: 'https:',
      path: '/api/v1/channel/name/shlorox',
      method: 'GET',
      headers: [Object: null prototype],
      agents: [Object],
      auth: undefined,
      beforeRedirect: [Function: dispatchBeforeRedirect],
      beforeRedirects: [Object],
      hostname: 'bck.gany.resmedia.cc',
      port: '',
      agent: undefined,
      nativeProtocols: [Object],
      pathname: '/api/v1/channel/name/shlorox'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'GET /api/v1/channel/name/shlorox HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json\r\n' +
        'User-Agent: axios/1.2.2\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: bck.gany.resmedia.cc\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/api/v1/channel/name/shlorox',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'bck.gany.resmedia.cc',
      protocol: 'https:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kEndCalled)]: true,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(kUniqueHeaders)]: null
    },
    _currentUrl: 'https://bck.gany.resmedia.cc/api/v1/channel/name/shlorox',
    [Symbol(kCapture)]: false
  },
  cause: Error: connect ECONNREFUSED ***IPADDRESS***:443
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '***IPADDRESS**',
    port: 443
  }
}
HTTP API error TypeError: Cannot read properties of undefined (reading 'status')
    at /app/.next/server/chunks/235.js:39:26
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async useApi (/app/.next/server/chunks/235.js:59:26)
    at async getServerSideProps (/app/.next/server/pages/channels/[channelName].js:266:26)
    at async Object.renderToHTML (/app/node_modules/next/dist/server/render.js:507:20)
    at async doRender (/app/node_modules/next/dist/server/base-server.js:720:34)
    at async cacheEntry.responseCache.get.incrementalCache.incrementalCache (/app/node_modules/next/dist/server/base-server.js:828:28)
    at async /app/node_modules/next/dist/server/response-cache/index.js:83:36
TypeError: Cannot read properties of undefined (reading 'data')
    at useApi (/app/.next/server/chunks/235.js:69:37)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getServerSideProps (/app/.next/server/pages/channels/[channelName].js:266:26)
    at async Object.renderToHTML (/app/node_modules/next/dist/server/render.js:507:20)
    at async doRender (/app/node_modules/next/dist/server/base-server.js:720:34)
    at async cacheEntry.responseCache.get.incrementalCache.incrementalCache (/app/node_modules/next/dist/server/base-server.js:828:28)
    at async /app/node_modules/next/dist/server/response-cache/index.js:83:36`

**Comment by Zibbp** [comment]
Are you using a reverse proxy? Or HTTP via an IP address? If you could please post a redacted version of your docker-compose.yml

**Comment by Smallinger** [comment]
yes i use a reverse proxy

here is my docker-compose
version: '3.3'
services:
  ganymede-api:
    container_name: ganymede-api
    image: ghcr.io/zibbp/ganymede:latest
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin # Set to your timezone
      - DB_HOST=ganymede-db
      - DB_PORT=5432
      - DB_USER=ganymede
      - DB_PASS=********************
      - DB_NAME=ganymede-prd
      - DB_SSL=disable
      - JWT_SECRET=*************************
      - JWT_REFRESH_SECRET=**************************
      - TWITCH_CLIENT_ID=***************************
      - TWITCH_CLIENT_SECRET=****************************
      - FRONTEND_HOST=https://frontend.example.com
      # OPTIONAL
      # - OAUTH_PROVIDER_URL=
      # - OAUTH_CLIENT_ID=
      # - OAUTH_CLIENT_SECRET=
      # - OAUTH_REDIRECT_URL=http://IP:PORT/api/v1/auth/oauth/callback # Points to the API service
    volumes:
      - /opt/gany-data/vod/storage:/vods
      - /opt/gany-data/logs:/logs
      - /opt/gany-data/data:/data
      # Uncomment below to persist temp files
      #- ./tmp:/tmp
    ports:
      - 4800:4000
  ganymede-frontend:
    container_name: ganymede-frontend
    image: ghcr.io/zibbp/ganymede-frontend:latest
    restart: unless-stopped
    environment:
      - API_URL=https://backend.example.com # Points to the API service
      - CDN_URL=https://cdn.example.com # Points to the CDN service
      - SHOW_SSO_LOGIN_BUTTON=false # show/hide SSO login button on login page
      - FORCE_SSO_AUTH=false # force SSO auth for all users (bypasses login page and redirects to SSO)
    ports:
      - 4801:3000
  ganymede-db:
    container_name: ganymede-db
    image: postgres:14
    volumes:
      - /opt/gany-data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=************************
      - POSTGRES_USER=ganymede
      - POSTGRES_DB=ganymede-prd
    ports:
      - 4803:5432
  ganymede-nginx:
    container_name: ganymede-nginx
    image: nginx
    volumes:
      - /opt/gany-data/nginx.conf:/etc/nginx/nginx.conf:ro
      - /opt/gany-data/vod/storage:/mnt/vods
    ports:
      - 4802:8080
networks:
  default:
    name: nginx-proxy
    external: true

**Comment by Zibbp** [comment]
Everything looks OK in the compose file. It may be a networking issue with the frontend container. When visiting a route such as `/channel/name`, there is some server side code that is used to fetch the channel via the container instead of your browser. I'm wondering if the frontend-container is unable to access the API via your reverse proxy. Try execing into the container and curling the API.
1. `docker exec -it -u root ganymede-frontend /bin/ash`
2. `apk add curl`
3. `curl https://backend.example.com`
4. 
The curl response should be "Ganymede API".

**Comment by Smallinger** [comment]
hmm thats wired, i can curl google.de with no issues, or other pages.
but if i try that with my domain, i got this error
`curl: (7) Failed to connect to ******* port 443: Connection refused`

The weird thing is ping works normal.

I build now a image for my Raspberry Pi, that its my 4-bay NAS @home, its looks like that is working.
https://github.com/Zibbp/ganymede/issues/86

I think i have a problem with my network configuration on my proxmox Dedicated Server, i think i investigate later more time in it,for now i working on my Pi Dockerfile a littlebit.

**Comment by Smallinger** [comment]
last update ^^

Now its working, what i did was 

1. `docker exec -it -u root ganymede-frontend /bin/ash`
2. `apk add nano`
3. `nano /etc/hosts`
add this line
192.168**** ***MYDOMAIN*** ***MYBACKENDDOMAIN***

i think i missconfigurate pFSense or Proxmox.

**Comment by infuse765** [comment]
I also modified the hosts file and it works. thank you!

**Comment by Zibbp** [comment]
If you're modifying the hosts file *inside* the container it is going to be reset every time the container restarts. You could try mounting the hosts file via a volume or changing some dns on your server to point to your reverse proxy.
