### ISSUE TITLE
chat render fails

### ISSUE THREAD

**Issue by flip-k** [Zibbp/ganymede#81]
Hello,

The "Chat Render" task failed multiple times at exactly 26% without any error in the log, but the container log shows this:

```
{"level":"error","error":"signal: segmentation fault (core dumped)","time":"2023-01-16T13:50:15+01:00","message":"error running TwitchDownloaderCLI for vod chat render"}
{"level":"error","error":"exit status 1","time":"2023-01-16T13:50:15+01:00","message":"error checking chat render logfile for no messages"}
{"level":"error","error":"exit status 1","time":"2023-01-16T13:50:15+01:00","message":"error rendering chat"}
```

here the live-chat file: 
[Archive.zip](https://github.com/Zibbp/ganymede/files/10428634/Archive.zip)

I'm using the latest version of both containers and I'm not changing the uids in the docker-compose

**Comment by Zibbp** [comment]
It appears I removed too many fallback fonts in a recent release. There is a chat message in a language that isn't supported by Inter so a fallback font is required. I added back more fallback fonts and was able to render the chat https://github.com/Zibbp/ganymede/commit/d678d143f3a95c232da66b097e86e55c43db7ff3.

I just pushed out a new release [v1.1.9](https://github.com/Zibbp/ganymede/releases/tag/v1.1.9) which has the extra fallback fonts included along with some other features. Let me know if you have any issues.
