### ISSUE TITLE
Force login and view count

### ISSUE THREAD

**Issue by CappiSteijns** [Zibbp/ganymede#85]
Hello,

Today I fired up this amazing project on Unraid. 

Everything is going well but I wondered if it would be possible if users could only watch archived videos when they have an account and are logged in. Now they can just access the page and watch all the content without being logged in. 

And would it be possible to see how many people have seen the archived video?

Thank you!

**Comment by Zibbp** [comment]
Hi,
I can look into implementing an optional feature that will require users to be logged in to view videos. As for a user view count for videos I think that is out of scope for the project.

**Comment by CappiSteijns** [comment]
> Hi,
> I can look into implementing an optional feature that will require users to be logged in to view videos. As for a user view count for videos I think that is out of scope for the project.

Understandable about the view count. Looking forward to the requirement to be logged in!

Thanks!

**Comment by Zibbp** [comment]
The "login to view this video" feature has been implemented in [v1.1.9](https://github.com/Zibbp/ganymede-frontend/releases/tag/v1.1.9). To enable this feature add an environment variable named `REQUIRE_LOGIN` to the frontend container setting the value to `true` like so `REQUIRE_LOGIN=true`. More information can be found on the release page. Please let me know if you have any issues with this feature.
