### ISSUE TITLE
little question, about render chat.

### ISSUE THREAD

**Issue by Smallinger** [Zibbp/ganymede#91]
Hey, is the Chat Playback on the webpanel working, if i disable chat render on watched channels? or did i need booth options turn on. 
Because the TwitchDownloadCLI doesn't support ffmpeg options for hardware acceleration and yesterday's stream was 6 hours and 8 hours after this is just chat rendering on the Raspberry Pi.

![image](https://user-images.githubusercontent.com/8080568/214226290-876c20b4-ea5f-47ef-b777-0e2574a2a1ad.png)

**Comment by Zibbp** [comment]
Hi, that toggle is supposed to disable chat rendering while downloading the chat. A user reported a bug yesterday that was causing this to not work when archiving past videos. I fixed that in https://github.com/Zibbp/ganymede/commit/2c32b7b574ffa40c1979de893aad381af119b6d2 and just waiting to create a release that has this fix. I'll update this issue when that release is published.

**Comment by Smallinger** [comment]
Hey thanks, 

i pulled the last git and create a new image for my Raspberry Pi and now it skip the step "chat render" and chat playback in my browser still works, perfect.
