### ISSUE TITLE
Video conversion failed - exit status 1

### ISSUE THREAD

**Issue by CappiSteijns** [Zibbp/ganymede#92]
Hi,

Yesterday I recorded the first **livestream**. But it fails at "video convert".

![image](https://user-images.githubusercontent.com/84481241/214315045-8e187354-fc0d-4e23-8e19-1c660c49f634.png)

![image](https://user-images.githubusercontent.com/84481241/214315103-1b43666f-5097-4513-afb3-7ce5a3a6550a.png)

![image](https://user-images.githubusercontent.com/84481241/214315195-6e0a4be8-d805-4d9a-9902-251139ebb2f9.png)
**API docker log**

I have tried restarting the **Video Convert**.

Any tips on what it could be and how to fix it?

Thanks!:)

**Comment by Zibbp** [comment]
Hi,
It looks like there are some corrupt packets in the video from the downloading. It *may* still be playable, but I would extract the video out of the container first so you don't lose it. To do so, perform the following.

1. Create a shell in the container via `docker exec -it ganymede-api /bin/bash` or via any other methods.
2. Find the video in `/tmp`.
3. Copy the video to your `/vods` folder which is mounted.
    4. `mv /tmp/video.mp4 /vods/video.mp4`.

I would then try playing the video in VLC or a similar program to see if it can be played. If it can be, move the video to the destination folder. If it has issues being played you may have to do some research into the ffmpeg errors and see if it can be recovered.

Once the video is safely out of the container you can manually delete the queue item in Admin > Queue and update the video in Admin > VODs to disable processing.

**Comment by Zibbp** [comment]
The `/tmp` docker volume does not need to be enabled, but helpful in the event of a container restart.

You are able to manually enter the container console and move files from `/tmp` to `/vods` without needing that docker volume enabled. One issue if it's not enable is any restart of the container will remove all files in `/tmp`. Hope that makes sense.

**Comment by CappiSteijns** [comment]
> 

Thanks for the clarification! Will enable /temp just to make sure. Restarted my server yesterday so files are not there anymore. Fortunatly I can download the vod again. 

Thanks!
